// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: AlertsManager.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace SAIC.Valkyrie.Api.V1 {

  /// <summary>Holder for reflection information generated from AlertsManager.proto</summary>
  public static partial class AlertsManagerReflection {

    #region Descriptor
    /// <summary>File descriptor for AlertsManager.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AlertsManagerReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChNBbGVydHNNYW5hZ2VyLnByb3RvEhtzYWljLnZhbGt5cmllLnNkay5nZW5l",
            "cmF0ZWQaG2dvb2dsZS9wcm90b2J1Zi9lbXB0eS5wcm90bxoMQ29tbW9uLnBy",
            "b3RvGhJTeXN0ZW1BbGVydHMucHJvdG8ifgoYQ2xpZW50QWxlcnRzU3Vic2Ny",
            "aXB0aW9uEh8KF3N1YnNjcmliZVRvRGV2aWNlQWxlcnRzGAEgASgIEiAKGHN1",
            "YnNjcmliZVRvU2VydmljZUFsZXJ0cxgCIAEoCBIfChdzdWJzY3JpYmVUb0Ns",
            "aWVudEFsZXJ0cxgDIAEoCCJVChpBbGVydHNTdWJzY3JpcHRpb25SZXNwb25z",
            "ZRI3CgVhbGVydBgBIAEoCzIoLnNhaWMudmFsa3lyaWUuc2RrLmdlbmVyYXRl",
            "ZC5TeXN0ZW1BbGVydCIoChVBbGVydERpc21pc3NhbFJlcXVlc3QSDwoHYWxl",
            "cnRJZBgBIAEoCTKGBAoNQWxlcnRzTWFuYWdlchJOCgpnZXRWZXJzaW9uEhYu",
            "Z29vZ2xlLnByb3RvYnVmLkVtcHR5Giguc2FpYy52YWxreXJpZS5zZGsuZ2Vu",
            "ZXJhdGVkLlZlcnNpb25JbmZvElUKD2dldFJlY2VudEFsZXJ0cxIWLmdvb2ds",
            "ZS5wcm90b2J1Zi5FbXB0eRooLnNhaWMudmFsa3lyaWUuc2RrLmdlbmVyYXRl",
            "ZC5TeXN0ZW1BbGVydDABEm0KDGRpc21pc3NBbGVydBIyLnNhaWMudmFsa3ly",
            "aWUuc2RrLmdlbmVyYXRlZC5BbGVydERpc21pc3NhbFJlcXVlc3QaKS5zYWlj",
            "LnZhbGt5cmllLnNkay5nZW5lcmF0ZWQuUmVzcG9uc2VJbmZvEmAKCXNlbmRB",
            "bGVydBIoLnNhaWMudmFsa3lyaWUuc2RrLmdlbmVyYXRlZC5TeXN0ZW1BbGVy",
            "dBopLnNhaWMudmFsa3lyaWUuc2RrLmdlbmVyYXRlZC5SZXNwb25zZUluZm8S",
            "fQoJc3Vic2NyaWJlEjUuc2FpYy52YWxreXJpZS5zZGsuZ2VuZXJhdGVkLkNs",
            "aWVudEFsZXJ0c1N1YnNjcmlwdGlvbho3LnNhaWMudmFsa3lyaWUuc2RrLmdl",
            "bmVyYXRlZC5BbGVydHNTdWJzY3JpcHRpb25SZXNwb25zZTABQm4KG3NhaWMu",
            "dmFsa3lyaWUuc2RrLmdlbmVyYXRlZEISQWxlcnRzTWFuYWdlclByb3RvWiRn",
            "aXRodWIuY29tL3RtaG9sdC9HZW5Eb2NQcm90by9zZGsvZ2+qAhRTQUlDLlZh",
            "bGt5cmllLkFwaS5WMWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, global::SAIC.Valkyrie.Api.V1.CommonReflection.Descriptor, global::SAIC.Valkyrie.Api.V1.SystemAlertsReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::SAIC.Valkyrie.Api.V1.ClientAlertsSubscription), global::SAIC.Valkyrie.Api.V1.ClientAlertsSubscription.Parser, new[]{ "SubscribeToDeviceAlerts", "SubscribeToServiceAlerts", "SubscribeToClientAlerts" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::SAIC.Valkyrie.Api.V1.AlertsSubscriptionResponse), global::SAIC.Valkyrie.Api.V1.AlertsSubscriptionResponse.Parser, new[]{ "Alert" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::SAIC.Valkyrie.Api.V1.AlertDismissalRequest), global::SAIC.Valkyrie.Api.V1.AlertDismissalRequest.Parser, new[]{ "AlertId" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  ///
  /// The ClientAlertsSubscription message is used to subscribe a client to the AlertsManager. It
  /// provides the specific alert types that the client would like to receive.
  /// </summary>
  public sealed partial class ClientAlertsSubscription : pb::IMessage<ClientAlertsSubscription>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ClientAlertsSubscription> _parser = new pb::MessageParser<ClientAlertsSubscription>(() => new ClientAlertsSubscription());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ClientAlertsSubscription> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SAIC.Valkyrie.Api.V1.AlertsManagerReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ClientAlertsSubscription() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ClientAlertsSubscription(ClientAlertsSubscription other) : this() {
      subscribeToDeviceAlerts_ = other.subscribeToDeviceAlerts_;
      subscribeToServiceAlerts_ = other.subscribeToServiceAlerts_;
      subscribeToClientAlerts_ = other.subscribeToClientAlerts_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ClientAlertsSubscription Clone() {
      return new ClientAlertsSubscription(this);
    }

    /// <summary>Field number for the "subscribeToDeviceAlerts" field.</summary>
    public const int SubscribeToDeviceAlertsFieldNumber = 1;
    private bool subscribeToDeviceAlerts_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool SubscribeToDeviceAlerts {
      get { return subscribeToDeviceAlerts_; }
      set {
        subscribeToDeviceAlerts_ = value;
      }
    }

    /// <summary>Field number for the "subscribeToServiceAlerts" field.</summary>
    public const int SubscribeToServiceAlertsFieldNumber = 2;
    private bool subscribeToServiceAlerts_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool SubscribeToServiceAlerts {
      get { return subscribeToServiceAlerts_; }
      set {
        subscribeToServiceAlerts_ = value;
      }
    }

    /// <summary>Field number for the "subscribeToClientAlerts" field.</summary>
    public const int SubscribeToClientAlertsFieldNumber = 3;
    private bool subscribeToClientAlerts_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool SubscribeToClientAlerts {
      get { return subscribeToClientAlerts_; }
      set {
        subscribeToClientAlerts_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ClientAlertsSubscription);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ClientAlertsSubscription other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (SubscribeToDeviceAlerts != other.SubscribeToDeviceAlerts) return false;
      if (SubscribeToServiceAlerts != other.SubscribeToServiceAlerts) return false;
      if (SubscribeToClientAlerts != other.SubscribeToClientAlerts) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (SubscribeToDeviceAlerts != false) hash ^= SubscribeToDeviceAlerts.GetHashCode();
      if (SubscribeToServiceAlerts != false) hash ^= SubscribeToServiceAlerts.GetHashCode();
      if (SubscribeToClientAlerts != false) hash ^= SubscribeToClientAlerts.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (SubscribeToDeviceAlerts != false) {
        output.WriteRawTag(8);
        output.WriteBool(SubscribeToDeviceAlerts);
      }
      if (SubscribeToServiceAlerts != false) {
        output.WriteRawTag(16);
        output.WriteBool(SubscribeToServiceAlerts);
      }
      if (SubscribeToClientAlerts != false) {
        output.WriteRawTag(24);
        output.WriteBool(SubscribeToClientAlerts);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (SubscribeToDeviceAlerts != false) {
        output.WriteRawTag(8);
        output.WriteBool(SubscribeToDeviceAlerts);
      }
      if (SubscribeToServiceAlerts != false) {
        output.WriteRawTag(16);
        output.WriteBool(SubscribeToServiceAlerts);
      }
      if (SubscribeToClientAlerts != false) {
        output.WriteRawTag(24);
        output.WriteBool(SubscribeToClientAlerts);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (SubscribeToDeviceAlerts != false) {
        size += 1 + 1;
      }
      if (SubscribeToServiceAlerts != false) {
        size += 1 + 1;
      }
      if (SubscribeToClientAlerts != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ClientAlertsSubscription other) {
      if (other == null) {
        return;
      }
      if (other.SubscribeToDeviceAlerts != false) {
        SubscribeToDeviceAlerts = other.SubscribeToDeviceAlerts;
      }
      if (other.SubscribeToServiceAlerts != false) {
        SubscribeToServiceAlerts = other.SubscribeToServiceAlerts;
      }
      if (other.SubscribeToClientAlerts != false) {
        SubscribeToClientAlerts = other.SubscribeToClientAlerts;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            SubscribeToDeviceAlerts = input.ReadBool();
            break;
          }
          case 16: {
            SubscribeToServiceAlerts = input.ReadBool();
            break;
          }
          case 24: {
            SubscribeToClientAlerts = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            SubscribeToDeviceAlerts = input.ReadBool();
            break;
          }
          case 16: {
            SubscribeToServiceAlerts = input.ReadBool();
            break;
          }
          case 24: {
            SubscribeToClientAlerts = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ///
  /// The AlertsSubscriptionResponse message is sent back to subscribed clients as alerts occur within the system.
  /// It contains all of the details related to one system alert.
  /// </summary>
  public sealed partial class AlertsSubscriptionResponse : pb::IMessage<AlertsSubscriptionResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<AlertsSubscriptionResponse> _parser = new pb::MessageParser<AlertsSubscriptionResponse>(() => new AlertsSubscriptionResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<AlertsSubscriptionResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SAIC.Valkyrie.Api.V1.AlertsManagerReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AlertsSubscriptionResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AlertsSubscriptionResponse(AlertsSubscriptionResponse other) : this() {
      alert_ = other.alert_ != null ? other.alert_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AlertsSubscriptionResponse Clone() {
      return new AlertsSubscriptionResponse(this);
    }

    /// <summary>Field number for the "alert" field.</summary>
    public const int AlertFieldNumber = 1;
    private global::SAIC.Valkyrie.Api.V1.SystemAlert alert_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::SAIC.Valkyrie.Api.V1.SystemAlert Alert {
      get { return alert_; }
      set {
        alert_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as AlertsSubscriptionResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(AlertsSubscriptionResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Alert, other.Alert)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (alert_ != null) hash ^= Alert.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (alert_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Alert);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (alert_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Alert);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (alert_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Alert);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(AlertsSubscriptionResponse other) {
      if (other == null) {
        return;
      }
      if (other.alert_ != null) {
        if (alert_ == null) {
          Alert = new global::SAIC.Valkyrie.Api.V1.SystemAlert();
        }
        Alert.MergeFrom(other.Alert);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (alert_ == null) {
              Alert = new global::SAIC.Valkyrie.Api.V1.SystemAlert();
            }
            input.ReadMessage(Alert);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (alert_ == null) {
              Alert = new global::SAIC.Valkyrie.Api.V1.SystemAlert();
            }
            input.ReadMessage(Alert);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ///
  /// The AlertDismissalRequest message is used to dismiss an alert from the alerts manager. It is
  /// used in the {@link #dismissAlert() DismissAlert} RPC call.
  /// </summary>
  public sealed partial class AlertDismissalRequest : pb::IMessage<AlertDismissalRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<AlertDismissalRequest> _parser = new pb::MessageParser<AlertDismissalRequest>(() => new AlertDismissalRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<AlertDismissalRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SAIC.Valkyrie.Api.V1.AlertsManagerReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AlertDismissalRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AlertDismissalRequest(AlertDismissalRequest other) : this() {
      alertId_ = other.alertId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AlertDismissalRequest Clone() {
      return new AlertDismissalRequest(this);
    }

    /// <summary>Field number for the "alertId" field.</summary>
    public const int AlertIdFieldNumber = 1;
    private string alertId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string AlertId {
      get { return alertId_; }
      set {
        alertId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as AlertDismissalRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(AlertDismissalRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (AlertId != other.AlertId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (AlertId.Length != 0) hash ^= AlertId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (AlertId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(AlertId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (AlertId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(AlertId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (AlertId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AlertId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(AlertDismissalRequest other) {
      if (other == null) {
        return;
      }
      if (other.AlertId.Length != 0) {
        AlertId = other.AlertId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            AlertId = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            AlertId = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
