// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ConfigurationManager.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace SAIC.Valkyrie.Api.V1 {

  /// <summary>Holder for reflection information generated from ConfigurationManager.proto</summary>
  public static partial class ConfigurationManagerReflection {

    #region Descriptor
    /// <summary>File descriptor for ConfigurationManager.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ConfigurationManagerReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChpDb25maWd1cmF0aW9uTWFuYWdlci5wcm90bxIbc2FpYy52YWxreXJpZS5z",
            "ZGsuZ2VuZXJhdGVkGhtnb29nbGUvcHJvdG9idWYvZW1wdHkucHJvdG8aHmdv",
            "b2dsZS9wcm90b2J1Zi93cmFwcGVycy5wcm90bxoMQ29tbW9uLnByb3RvGg9T",
            "QU9iamVjdHMucHJvdG8aGVN5c3RlbUNvbmZpZ3VyYXRpb24ucHJvdG8iwgEK",
            "IENvbmZpZ3VyYXRpb25NYW5hZ2VyU3Vic2NyaXB0aW9uEhkKEXN1YnNjcmli",
            "ZVRvTGV2ZWxzGAEgASgIEiEKGXN1YnNjcmliZVRvUHJvdGVjdGVkQXJlYXMY",
            "AiABKAgSHAoUc3Vic2NyaWJlVG9TQU9iamVjdHMYAyABKAgSQgoJc2FSZXF1",
            "ZXN0GAQgASgLMi8uc2FpYy52YWxreXJpZS5zZGsuZ2VuZXJhdGVkLlNBT2Jq",
            "ZWN0R2V0UmVxdWVzdCLZAgohQ29uZmlndXJhdGlvblN1YnNjcmlwdGlvblJl",
            "c3BvbnNlEkQKBHR5cGUYASABKA4yNi5zYWljLnZhbGt5cmllLnNkay5nZW5l",
            "cmF0ZWQuQ29uZmlndXJhdGlvblJlc3BvbnNlVHlwZRJPCgZsZXZlbHMYAiAB",
            "KAsyPS5zYWljLnZhbGt5cmllLnNkay5nZW5lcmF0ZWQuU3lzdGVtTGV2ZWxz",
            "U3Vic2NyaXB0aW9uUmVzcG9uc2VIABJMCgJwYRgDIAEoCzI+LnNhaWMudmFs",
            "a3lyaWUuc2RrLmdlbmVyYXRlZC5Qcm90ZWN0ZWRBcmVhU3Vic2NyaXB0aW9u",
            "UmVzcG9uc2VIABJHCgJzYRgEIAEoCzI5LnNhaWMudmFsa3lyaWUuc2RrLmdl",
            "bmVyYXRlZC5TQU9iamVjdFN1YnNjcmlwdGlvblJlc3BvbnNlSABCBgoEZGF0",
            "YSKnAQohUHJvdGVjdGVkQXJlYVN1YnNjcmlwdGlvblJlc3BvbnNlEj0KBmNo",
            "YW5nZRgBIAEoDjItLnNhaWMudmFsa3lyaWUuc2RrLmdlbmVyYXRlZC5TeXN0",
            "ZW1DaGFuZ2VUeXBlEkMKAnBhGAIgASgLMjcuc2FpYy52YWxreXJpZS5zZGsu",
            "Z2VuZXJhdGVkLlByb3RlY3RlZEFyZWFDb25maWd1cmF0aW9uIqABCiBTeXN0",
            "ZW1MZXZlbHNTdWJzY3JpcHRpb25SZXNwb25zZRI9CgZjaGFuZ2UYASABKA4y",
            "LS5zYWljLnZhbGt5cmllLnNkay5nZW5lcmF0ZWQuU3lzdGVtQ2hhbmdlVHlw",
            "ZRI9CgZsZXZlbHMYAiABKAsyLS5zYWljLnZhbGt5cmllLnNkay5nZW5lcmF0",
            "ZWQuU3lzdGVtTGV2ZWxzSW5mbyLcAQoQU3lzdGVtTGV2ZWxzSW5mbxI2CgVs",
            "ZXZlbBgBIAEoDjInLnNhaWMudmFsa3lyaWUuc2RrLmdlbmVyYXRlZC5GUENP",
            "TkxldmVsEkgKDmNsYXNzaWZpY2F0aW9uGAIgASgOMjAuc2FpYy52YWxreXJp",
            "ZS5zZGsuZ2VuZXJhdGVkLkNsYXNzaWZpY2F0aW9uTGV2ZWwSIAoYc3lzdGVt",
            "U3VwcG9ydHNGUENvbkxldmVsGAMgASgIEiQKHHN5c3RlbVN1cHBvcnRzQ2xh",
            "c3NpZmljYXRpb24YBCABKAgiZAodU2VydmljZXNDb25maWd1cmF0aW9uUmVz",
            "cG9uc2USQwoIc2VydmljZXMYASADKAsyMS5zYWljLnZhbGt5cmllLnNkay5n",
            "ZW5lcmF0ZWQuU2VydmljZUNvbmZpZ3VyYXRpb24qtQEKGUNvbmZpZ3VyYXRp",
            "b25SZXNwb25zZVR5cGUSIgoeQ09ORklHVVJBVElPTl9SRVNQT05TRV9VTktO",
            "T1dOEAASIQodQ09ORklHVVJBVElPTl9SRVNQT05TRV9MRVZFTFMQARIqCiZD",
            "T05GSUdVUkFUSU9OX1JFU1BPTlNFX1BST1RFQ1RFRF9BUkVBUxACEiUKIUNP",
            "TkZJR1VSQVRJT05fUkVTUE9OU0VfU0FfT0JKRUNUUxADMqYKChRDb25maWd1",
            "cmF0aW9uTWFuYWdlchJOCgpnZXRWZXJzaW9uEhYuZ29vZ2xlLnByb3RvYnVm",
            "LkVtcHR5Giguc2FpYy52YWxreXJpZS5zZGsuZ2VuZXJhdGVkLlZlcnNpb25J",
            "bmZvEmYKEWdldFByb3RlY3RlZEFyZWFzEhYuZ29vZ2xlLnByb3RvYnVmLkVt",
            "cHR5Gjcuc2FpYy52YWxreXJpZS5zZGsuZ2VuZXJhdGVkLlByb3RlY3RlZEFy",
            "ZWFDb25maWd1cmF0aW9uMAESWAoPZ2V0U3lzdGVtTGV2ZWxzEhYuZ29vZ2xl",
            "LnByb3RvYnVmLkVtcHR5Gi0uc2FpYy52YWxreXJpZS5zZGsuZ2VuZXJhdGVk",
            "LlN5c3RlbUxldmVsc0luZm8SawoPc2V0U3lzdGVtTGV2ZWxzEi0uc2FpYy52",
            "YWxreXJpZS5zZGsuZ2VuZXJhdGVkLlN5c3RlbUxldmVsc0luZm8aKS5zYWlj",
            "LnZhbGt5cmllLnNkay5nZW5lcmF0ZWQuUmVzcG9uc2VJbmZvEowBCglzdWJz",
            "Y3JpYmUSPS5zYWljLnZhbGt5cmllLnNkay5nZW5lcmF0ZWQuQ29uZmlndXJh",
            "dGlvbk1hbmFnZXJTdWJzY3JpcHRpb24aPi5zYWljLnZhbGt5cmllLnNkay5n",
            "ZW5lcmF0ZWQuQ29uZmlndXJhdGlvblN1YnNjcmlwdGlvblJlc3BvbnNlMAES",
            "WwoPZ2V0U3lzdGVtQ29uZmlnEhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5GjAu",
            "c2FpYy52YWxreXJpZS5zZGsuZ2VuZXJhdGVkLlN5c3RlbUNvbmZpZ3VyYXRp",
            "b24SZwoRZ2V0U2VydmljZXNDb25maWcSFi5nb29nbGUucHJvdG9idWYuRW1w",
            "dHkaOi5zYWljLnZhbGt5cmllLnNkay5nZW5lcmF0ZWQuU2VydmljZXNDb25m",
            "aWd1cmF0aW9uUmVzcG9uc2USfAoMZ2V0U0FPYmplY3RzEi8uc2FpYy52YWxr",
            "eXJpZS5zZGsuZ2VuZXJhdGVkLlNBT2JqZWN0R2V0UmVxdWVzdBo5LnNhaWMu",
            "dmFsa3lyaWUuc2RrLmdlbmVyYXRlZC5TQU9iamVjdFN1YnNjcmlwdGlvblJl",
            "c3BvbnNlMAESSwoRZ2V0U0FPYmplY3RHcm91cHMSFi5nb29nbGUucHJvdG9i",
            "dWYuRW1wdHkaHC5nb29nbGUucHJvdG9idWYuU3RyaW5nVmFsdWUwARJ5Cg5j",
            "cmVhdGVTQU9iamVjdBIyLnNhaWMudmFsa3lyaWUuc2RrLmdlbmVyYXRlZC5T",
            "QU9iamVjdFVwZGF0ZVJlcXVlc3QaMy5zYWljLnZhbGt5cmllLnNkay5nZW5l",
            "cmF0ZWQuU0FPYmplY3RVcGRhdGVSZXNwb25zZRJ5Cg51cGRhdGVTQU9iamVj",
            "dBIyLnNhaWMudmFsa3lyaWUuc2RrLmdlbmVyYXRlZC5TQU9iamVjdFVwZGF0",
            "ZVJlcXVlc3QaMy5zYWljLnZhbGt5cmllLnNkay5nZW5lcmF0ZWQuU0FPYmpl",
            "Y3RVcGRhdGVSZXNwb25zZRJ5Cg5kZWxldGVTQU9iamVjdBIyLnNhaWMudmFs",
            "a3lyaWUuc2RrLmdlbmVyYXRlZC5TQU9iamVjdERlbGV0ZVJlcXVlc3QaMy5z",
            "YWljLnZhbGt5cmllLnNkay5nZW5lcmF0ZWQuU0FPYmplY3RVcGRhdGVSZXNw",
            "b25zZUJ1ChtzYWljLnZhbGt5cmllLnNkay5nZW5lcmF0ZWRCGUNvbmZpZ3Vy",
            "YXRpb25NYW5hZ2VyUHJvdG9aJGdpdGh1Yi5jb20vdG1ob2x0L0dlbkRvY1By",
            "b3RvL3Nkay9nb6oCFFNBSUMuVmFsa3lyaWUuQXBpLlYxYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.WrappersReflection.Descriptor, global::SAIC.Valkyrie.Api.V1.CommonReflection.Descriptor, global::SAIC.Valkyrie.Api.V1.SAObjectsReflection.Descriptor, global::SAIC.Valkyrie.Api.V1.SystemConfigurationReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::SAIC.Valkyrie.Api.V1.ConfigurationResponseType), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::SAIC.Valkyrie.Api.V1.ConfigurationManagerSubscription), global::SAIC.Valkyrie.Api.V1.ConfigurationManagerSubscription.Parser, new[]{ "SubscribeToLevels", "SubscribeToProtectedAreas", "SubscribeToSAObjects", "SaRequest" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::SAIC.Valkyrie.Api.V1.ConfigurationSubscriptionResponse), global::SAIC.Valkyrie.Api.V1.ConfigurationSubscriptionResponse.Parser, new[]{ "Type", "Levels", "Pa", "Sa" }, new[]{ "Data" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::SAIC.Valkyrie.Api.V1.ProtectedAreaSubscriptionResponse), global::SAIC.Valkyrie.Api.V1.ProtectedAreaSubscriptionResponse.Parser, new[]{ "Change", "Pa" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::SAIC.Valkyrie.Api.V1.SystemLevelsSubscriptionResponse), global::SAIC.Valkyrie.Api.V1.SystemLevelsSubscriptionResponse.Parser, new[]{ "Change", "Levels" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::SAIC.Valkyrie.Api.V1.SystemLevelsInfo), global::SAIC.Valkyrie.Api.V1.SystemLevelsInfo.Parser, new[]{ "Level", "Classification", "SystemSupportsFPConLevel", "SystemSupportsClassification" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::SAIC.Valkyrie.Api.V1.ServicesConfigurationResponse), global::SAIC.Valkyrie.Api.V1.ServicesConfigurationResponse.Parser, new[]{ "Services" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  ///
  /// When a client receives a ConfigurationSubscriptionResponse, it will be an update to one of the
  /// sets of information being handled by the configuration manager. This enumeration defines which piece is being
  /// returned.
  /// </summary>
  public enum ConfigurationResponseType {
    [pbr::OriginalName("CONFIGURATION_RESPONSE_UNKNOWN")] ConfigurationResponseUnknown = 0,
    [pbr::OriginalName("CONFIGURATION_RESPONSE_LEVELS")] ConfigurationResponseLevels = 1,
    [pbr::OriginalName("CONFIGURATION_RESPONSE_PROTECTED_AREAS")] ConfigurationResponseProtectedAreas = 2,
    [pbr::OriginalName("CONFIGURATION_RESPONSE_SA_OBJECTS")] ConfigurationResponseSaObjects = 3,
  }

  #endregion

  #region Messages
  /// <summary>
  ///
  /// The ConfigurationManagerSubscription message contains inbound details for subscribing
  /// to the configuration manager.
  /// </summary>
  public sealed partial class ConfigurationManagerSubscription : pb::IMessage<ConfigurationManagerSubscription>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ConfigurationManagerSubscription> _parser = new pb::MessageParser<ConfigurationManagerSubscription>(() => new ConfigurationManagerSubscription());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ConfigurationManagerSubscription> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SAIC.Valkyrie.Api.V1.ConfigurationManagerReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ConfigurationManagerSubscription() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ConfigurationManagerSubscription(ConfigurationManagerSubscription other) : this() {
      subscribeToLevels_ = other.subscribeToLevels_;
      subscribeToProtectedAreas_ = other.subscribeToProtectedAreas_;
      subscribeToSAObjects_ = other.subscribeToSAObjects_;
      saRequest_ = other.saRequest_ != null ? other.saRequest_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ConfigurationManagerSubscription Clone() {
      return new ConfigurationManagerSubscription(this);
    }

    /// <summary>Field number for the "subscribeToLevels" field.</summary>
    public const int SubscribeToLevelsFieldNumber = 1;
    private bool subscribeToLevels_;
    /// <summary>
    /// whether or not to receive changes to the system levels (classification, FPCON)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool SubscribeToLevels {
      get { return subscribeToLevels_; }
      set {
        subscribeToLevels_ = value;
      }
    }

    /// <summary>Field number for the "subscribeToProtectedAreas" field.</summary>
    public const int SubscribeToProtectedAreasFieldNumber = 2;
    private bool subscribeToProtectedAreas_;
    /// <summary>
    /// whether or not to receive changes to the set of SA objects in the system
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool SubscribeToProtectedAreas {
      get { return subscribeToProtectedAreas_; }
      set {
        subscribeToProtectedAreas_ = value;
      }
    }

    /// <summary>Field number for the "subscribeToSAObjects" field.</summary>
    public const int SubscribeToSAObjectsFieldNumber = 3;
    private bool subscribeToSAObjects_;
    /// <summary>
    /// whether or not to receive changes to the set of SA objects in the system
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool SubscribeToSAObjects {
      get { return subscribeToSAObjects_; }
      set {
        subscribeToSAObjects_ = value;
      }
    }

    /// <summary>Field number for the "saRequest" field.</summary>
    public const int SaRequestFieldNumber = 4;
    private global::SAIC.Valkyrie.Api.V1.SAObjectGetRequest saRequest_;
    /// <summary>
    /// the details for the subscription to SA objects
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::SAIC.Valkyrie.Api.V1.SAObjectGetRequest SaRequest {
      get { return saRequest_; }
      set {
        saRequest_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ConfigurationManagerSubscription);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ConfigurationManagerSubscription other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (SubscribeToLevels != other.SubscribeToLevels) return false;
      if (SubscribeToProtectedAreas != other.SubscribeToProtectedAreas) return false;
      if (SubscribeToSAObjects != other.SubscribeToSAObjects) return false;
      if (!object.Equals(SaRequest, other.SaRequest)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (SubscribeToLevels != false) hash ^= SubscribeToLevels.GetHashCode();
      if (SubscribeToProtectedAreas != false) hash ^= SubscribeToProtectedAreas.GetHashCode();
      if (SubscribeToSAObjects != false) hash ^= SubscribeToSAObjects.GetHashCode();
      if (saRequest_ != null) hash ^= SaRequest.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (SubscribeToLevels != false) {
        output.WriteRawTag(8);
        output.WriteBool(SubscribeToLevels);
      }
      if (SubscribeToProtectedAreas != false) {
        output.WriteRawTag(16);
        output.WriteBool(SubscribeToProtectedAreas);
      }
      if (SubscribeToSAObjects != false) {
        output.WriteRawTag(24);
        output.WriteBool(SubscribeToSAObjects);
      }
      if (saRequest_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(SaRequest);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (SubscribeToLevels != false) {
        output.WriteRawTag(8);
        output.WriteBool(SubscribeToLevels);
      }
      if (SubscribeToProtectedAreas != false) {
        output.WriteRawTag(16);
        output.WriteBool(SubscribeToProtectedAreas);
      }
      if (SubscribeToSAObjects != false) {
        output.WriteRawTag(24);
        output.WriteBool(SubscribeToSAObjects);
      }
      if (saRequest_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(SaRequest);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (SubscribeToLevels != false) {
        size += 1 + 1;
      }
      if (SubscribeToProtectedAreas != false) {
        size += 1 + 1;
      }
      if (SubscribeToSAObjects != false) {
        size += 1 + 1;
      }
      if (saRequest_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(SaRequest);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ConfigurationManagerSubscription other) {
      if (other == null) {
        return;
      }
      if (other.SubscribeToLevels != false) {
        SubscribeToLevels = other.SubscribeToLevels;
      }
      if (other.SubscribeToProtectedAreas != false) {
        SubscribeToProtectedAreas = other.SubscribeToProtectedAreas;
      }
      if (other.SubscribeToSAObjects != false) {
        SubscribeToSAObjects = other.SubscribeToSAObjects;
      }
      if (other.saRequest_ != null) {
        if (saRequest_ == null) {
          SaRequest = new global::SAIC.Valkyrie.Api.V1.SAObjectGetRequest();
        }
        SaRequest.MergeFrom(other.SaRequest);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            SubscribeToLevels = input.ReadBool();
            break;
          }
          case 16: {
            SubscribeToProtectedAreas = input.ReadBool();
            break;
          }
          case 24: {
            SubscribeToSAObjects = input.ReadBool();
            break;
          }
          case 34: {
            if (saRequest_ == null) {
              SaRequest = new global::SAIC.Valkyrie.Api.V1.SAObjectGetRequest();
            }
            input.ReadMessage(SaRequest);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            SubscribeToLevels = input.ReadBool();
            break;
          }
          case 16: {
            SubscribeToProtectedAreas = input.ReadBool();
            break;
          }
          case 24: {
            SubscribeToSAObjects = input.ReadBool();
            break;
          }
          case 34: {
            if (saRequest_ == null) {
              SaRequest = new global::SAIC.Valkyrie.Api.V1.SAObjectGetRequest();
            }
            input.ReadMessage(SaRequest);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ///
  /// The ConfigurationSubscriptionResponse message is a wrapper around a configuration manager subscription
  /// response. Based on client subscription it could be a change to levels, protected areas, or an SA object.
  /// </summary>
  public sealed partial class ConfigurationSubscriptionResponse : pb::IMessage<ConfigurationSubscriptionResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ConfigurationSubscriptionResponse> _parser = new pb::MessageParser<ConfigurationSubscriptionResponse>(() => new ConfigurationSubscriptionResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ConfigurationSubscriptionResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SAIC.Valkyrie.Api.V1.ConfigurationManagerReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ConfigurationSubscriptionResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ConfigurationSubscriptionResponse(ConfigurationSubscriptionResponse other) : this() {
      type_ = other.type_;
      switch (other.DataCase) {
        case DataOneofCase.Levels:
          Levels = other.Levels.Clone();
          break;
        case DataOneofCase.Pa:
          Pa = other.Pa.Clone();
          break;
        case DataOneofCase.Sa:
          Sa = other.Sa.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ConfigurationSubscriptionResponse Clone() {
      return new ConfigurationSubscriptionResponse(this);
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private global::SAIC.Valkyrie.Api.V1.ConfigurationResponseType type_ = global::SAIC.Valkyrie.Api.V1.ConfigurationResponseType.ConfigurationResponseUnknown;
    /// <summary>
    /// what type of data is represented here
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::SAIC.Valkyrie.Api.V1.ConfigurationResponseType Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "levels" field.</summary>
    public const int LevelsFieldNumber = 2;
    /// <summary>
    /// system levels specific data
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::SAIC.Valkyrie.Api.V1.SystemLevelsSubscriptionResponse Levels {
      get { return dataCase_ == DataOneofCase.Levels ? (global::SAIC.Valkyrie.Api.V1.SystemLevelsSubscriptionResponse) data_ : null; }
      set {
        data_ = value;
        dataCase_ = value == null ? DataOneofCase.None : DataOneofCase.Levels;
      }
    }

    /// <summary>Field number for the "pa" field.</summary>
    public const int PaFieldNumber = 3;
    /// <summary>
    /// protected area specific data
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::SAIC.Valkyrie.Api.V1.ProtectedAreaSubscriptionResponse Pa {
      get { return dataCase_ == DataOneofCase.Pa ? (global::SAIC.Valkyrie.Api.V1.ProtectedAreaSubscriptionResponse) data_ : null; }
      set {
        data_ = value;
        dataCase_ = value == null ? DataOneofCase.None : DataOneofCase.Pa;
      }
    }

    /// <summary>Field number for the "sa" field.</summary>
    public const int SaFieldNumber = 4;
    /// <summary>
    /// SA object specific data
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::SAIC.Valkyrie.Api.V1.SAObjectSubscriptionResponse Sa {
      get { return dataCase_ == DataOneofCase.Sa ? (global::SAIC.Valkyrie.Api.V1.SAObjectSubscriptionResponse) data_ : null; }
      set {
        data_ = value;
        dataCase_ = value == null ? DataOneofCase.None : DataOneofCase.Sa;
      }
    }

    private object data_;
    /// <summary>Enum of possible cases for the "data" oneof.</summary>
    public enum DataOneofCase {
      None = 0,
      Levels = 2,
      Pa = 3,
      Sa = 4,
    }
    private DataOneofCase dataCase_ = DataOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DataOneofCase DataCase {
      get { return dataCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearData() {
      dataCase_ = DataOneofCase.None;
      data_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ConfigurationSubscriptionResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ConfigurationSubscriptionResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      if (!object.Equals(Levels, other.Levels)) return false;
      if (!object.Equals(Pa, other.Pa)) return false;
      if (!object.Equals(Sa, other.Sa)) return false;
      if (DataCase != other.DataCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Type != global::SAIC.Valkyrie.Api.V1.ConfigurationResponseType.ConfigurationResponseUnknown) hash ^= Type.GetHashCode();
      if (dataCase_ == DataOneofCase.Levels) hash ^= Levels.GetHashCode();
      if (dataCase_ == DataOneofCase.Pa) hash ^= Pa.GetHashCode();
      if (dataCase_ == DataOneofCase.Sa) hash ^= Sa.GetHashCode();
      hash ^= (int) dataCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Type != global::SAIC.Valkyrie.Api.V1.ConfigurationResponseType.ConfigurationResponseUnknown) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (dataCase_ == DataOneofCase.Levels) {
        output.WriteRawTag(18);
        output.WriteMessage(Levels);
      }
      if (dataCase_ == DataOneofCase.Pa) {
        output.WriteRawTag(26);
        output.WriteMessage(Pa);
      }
      if (dataCase_ == DataOneofCase.Sa) {
        output.WriteRawTag(34);
        output.WriteMessage(Sa);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Type != global::SAIC.Valkyrie.Api.V1.ConfigurationResponseType.ConfigurationResponseUnknown) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (dataCase_ == DataOneofCase.Levels) {
        output.WriteRawTag(18);
        output.WriteMessage(Levels);
      }
      if (dataCase_ == DataOneofCase.Pa) {
        output.WriteRawTag(26);
        output.WriteMessage(Pa);
      }
      if (dataCase_ == DataOneofCase.Sa) {
        output.WriteRawTag(34);
        output.WriteMessage(Sa);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Type != global::SAIC.Valkyrie.Api.V1.ConfigurationResponseType.ConfigurationResponseUnknown) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (dataCase_ == DataOneofCase.Levels) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Levels);
      }
      if (dataCase_ == DataOneofCase.Pa) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Pa);
      }
      if (dataCase_ == DataOneofCase.Sa) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Sa);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ConfigurationSubscriptionResponse other) {
      if (other == null) {
        return;
      }
      if (other.Type != global::SAIC.Valkyrie.Api.V1.ConfigurationResponseType.ConfigurationResponseUnknown) {
        Type = other.Type;
      }
      switch (other.DataCase) {
        case DataOneofCase.Levels:
          if (Levels == null) {
            Levels = new global::SAIC.Valkyrie.Api.V1.SystemLevelsSubscriptionResponse();
          }
          Levels.MergeFrom(other.Levels);
          break;
        case DataOneofCase.Pa:
          if (Pa == null) {
            Pa = new global::SAIC.Valkyrie.Api.V1.ProtectedAreaSubscriptionResponse();
          }
          Pa.MergeFrom(other.Pa);
          break;
        case DataOneofCase.Sa:
          if (Sa == null) {
            Sa = new global::SAIC.Valkyrie.Api.V1.SAObjectSubscriptionResponse();
          }
          Sa.MergeFrom(other.Sa);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Type = (global::SAIC.Valkyrie.Api.V1.ConfigurationResponseType) input.ReadEnum();
            break;
          }
          case 18: {
            global::SAIC.Valkyrie.Api.V1.SystemLevelsSubscriptionResponse subBuilder = new global::SAIC.Valkyrie.Api.V1.SystemLevelsSubscriptionResponse();
            if (dataCase_ == DataOneofCase.Levels) {
              subBuilder.MergeFrom(Levels);
            }
            input.ReadMessage(subBuilder);
            Levels = subBuilder;
            break;
          }
          case 26: {
            global::SAIC.Valkyrie.Api.V1.ProtectedAreaSubscriptionResponse subBuilder = new global::SAIC.Valkyrie.Api.V1.ProtectedAreaSubscriptionResponse();
            if (dataCase_ == DataOneofCase.Pa) {
              subBuilder.MergeFrom(Pa);
            }
            input.ReadMessage(subBuilder);
            Pa = subBuilder;
            break;
          }
          case 34: {
            global::SAIC.Valkyrie.Api.V1.SAObjectSubscriptionResponse subBuilder = new global::SAIC.Valkyrie.Api.V1.SAObjectSubscriptionResponse();
            if (dataCase_ == DataOneofCase.Sa) {
              subBuilder.MergeFrom(Sa);
            }
            input.ReadMessage(subBuilder);
            Sa = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Type = (global::SAIC.Valkyrie.Api.V1.ConfigurationResponseType) input.ReadEnum();
            break;
          }
          case 18: {
            global::SAIC.Valkyrie.Api.V1.SystemLevelsSubscriptionResponse subBuilder = new global::SAIC.Valkyrie.Api.V1.SystemLevelsSubscriptionResponse();
            if (dataCase_ == DataOneofCase.Levels) {
              subBuilder.MergeFrom(Levels);
            }
            input.ReadMessage(subBuilder);
            Levels = subBuilder;
            break;
          }
          case 26: {
            global::SAIC.Valkyrie.Api.V1.ProtectedAreaSubscriptionResponse subBuilder = new global::SAIC.Valkyrie.Api.V1.ProtectedAreaSubscriptionResponse();
            if (dataCase_ == DataOneofCase.Pa) {
              subBuilder.MergeFrom(Pa);
            }
            input.ReadMessage(subBuilder);
            Pa = subBuilder;
            break;
          }
          case 34: {
            global::SAIC.Valkyrie.Api.V1.SAObjectSubscriptionResponse subBuilder = new global::SAIC.Valkyrie.Api.V1.SAObjectSubscriptionResponse();
            if (dataCase_ == DataOneofCase.Sa) {
              subBuilder.MergeFrom(Sa);
            }
            input.ReadMessage(subBuilder);
            Sa = subBuilder;
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ///
  /// The ProtectedAreaSubscriptionResponse message contains details about one change to a protected area in
  /// the system. It provides details about the protected area and  what kind of change just occurred -
  /// a create/update/delete.
  /// </summary>
  public sealed partial class ProtectedAreaSubscriptionResponse : pb::IMessage<ProtectedAreaSubscriptionResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ProtectedAreaSubscriptionResponse> _parser = new pb::MessageParser<ProtectedAreaSubscriptionResponse>(() => new ProtectedAreaSubscriptionResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ProtectedAreaSubscriptionResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SAIC.Valkyrie.Api.V1.ConfigurationManagerReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProtectedAreaSubscriptionResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProtectedAreaSubscriptionResponse(ProtectedAreaSubscriptionResponse other) : this() {
      change_ = other.change_;
      pa_ = other.pa_ != null ? other.pa_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProtectedAreaSubscriptionResponse Clone() {
      return new ProtectedAreaSubscriptionResponse(this);
    }

    /// <summary>Field number for the "change" field.</summary>
    public const int ChangeFieldNumber = 1;
    private global::SAIC.Valkyrie.Api.V1.SystemChangeType change_ = global::SAIC.Valkyrie.Api.V1.SystemChangeType.ChangeTypeUnknown;
    /// <summary>
    /// the type of change that has occurred - add/update/delete
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::SAIC.Valkyrie.Api.V1.SystemChangeType Change {
      get { return change_; }
      set {
        change_ = value;
      }
    }

    /// <summary>Field number for the "pa" field.</summary>
    public const int PaFieldNumber = 2;
    private global::SAIC.Valkyrie.Api.V1.ProtectedAreaConfiguration pa_;
    /// <summary>
    /// the protected area details
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::SAIC.Valkyrie.Api.V1.ProtectedAreaConfiguration Pa {
      get { return pa_; }
      set {
        pa_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ProtectedAreaSubscriptionResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ProtectedAreaSubscriptionResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Change != other.Change) return false;
      if (!object.Equals(Pa, other.Pa)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Change != global::SAIC.Valkyrie.Api.V1.SystemChangeType.ChangeTypeUnknown) hash ^= Change.GetHashCode();
      if (pa_ != null) hash ^= Pa.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Change != global::SAIC.Valkyrie.Api.V1.SystemChangeType.ChangeTypeUnknown) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Change);
      }
      if (pa_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Pa);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Change != global::SAIC.Valkyrie.Api.V1.SystemChangeType.ChangeTypeUnknown) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Change);
      }
      if (pa_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Pa);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Change != global::SAIC.Valkyrie.Api.V1.SystemChangeType.ChangeTypeUnknown) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Change);
      }
      if (pa_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Pa);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ProtectedAreaSubscriptionResponse other) {
      if (other == null) {
        return;
      }
      if (other.Change != global::SAIC.Valkyrie.Api.V1.SystemChangeType.ChangeTypeUnknown) {
        Change = other.Change;
      }
      if (other.pa_ != null) {
        if (pa_ == null) {
          Pa = new global::SAIC.Valkyrie.Api.V1.ProtectedAreaConfiguration();
        }
        Pa.MergeFrom(other.Pa);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Change = (global::SAIC.Valkyrie.Api.V1.SystemChangeType) input.ReadEnum();
            break;
          }
          case 18: {
            if (pa_ == null) {
              Pa = new global::SAIC.Valkyrie.Api.V1.ProtectedAreaConfiguration();
            }
            input.ReadMessage(Pa);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Change = (global::SAIC.Valkyrie.Api.V1.SystemChangeType) input.ReadEnum();
            break;
          }
          case 18: {
            if (pa_ == null) {
              Pa = new global::SAIC.Valkyrie.Api.V1.ProtectedAreaConfiguration();
            }
            input.ReadMessage(Pa);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ///
  /// The SystemLevelsSubscriptionResponse message contains details regarding a change to system levels.
  /// </summary>
  public sealed partial class SystemLevelsSubscriptionResponse : pb::IMessage<SystemLevelsSubscriptionResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SystemLevelsSubscriptionResponse> _parser = new pb::MessageParser<SystemLevelsSubscriptionResponse>(() => new SystemLevelsSubscriptionResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SystemLevelsSubscriptionResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SAIC.Valkyrie.Api.V1.ConfigurationManagerReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SystemLevelsSubscriptionResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SystemLevelsSubscriptionResponse(SystemLevelsSubscriptionResponse other) : this() {
      change_ = other.change_;
      levels_ = other.levels_ != null ? other.levels_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SystemLevelsSubscriptionResponse Clone() {
      return new SystemLevelsSubscriptionResponse(this);
    }

    /// <summary>Field number for the "change" field.</summary>
    public const int ChangeFieldNumber = 1;
    private global::SAIC.Valkyrie.Api.V1.SystemChangeType change_ = global::SAIC.Valkyrie.Api.V1.SystemChangeType.ChangeTypeUnknown;
    /// <summary>
    /// the type of change that has occurred - add/update/delete
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::SAIC.Valkyrie.Api.V1.SystemChangeType Change {
      get { return change_; }
      set {
        change_ = value;
      }
    }

    /// <summary>Field number for the "levels" field.</summary>
    public const int LevelsFieldNumber = 2;
    private global::SAIC.Valkyrie.Api.V1.SystemLevelsInfo levels_;
    /// <summary>
    /// the system level details
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::SAIC.Valkyrie.Api.V1.SystemLevelsInfo Levels {
      get { return levels_; }
      set {
        levels_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SystemLevelsSubscriptionResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SystemLevelsSubscriptionResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Change != other.Change) return false;
      if (!object.Equals(Levels, other.Levels)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Change != global::SAIC.Valkyrie.Api.V1.SystemChangeType.ChangeTypeUnknown) hash ^= Change.GetHashCode();
      if (levels_ != null) hash ^= Levels.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Change != global::SAIC.Valkyrie.Api.V1.SystemChangeType.ChangeTypeUnknown) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Change);
      }
      if (levels_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Levels);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Change != global::SAIC.Valkyrie.Api.V1.SystemChangeType.ChangeTypeUnknown) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Change);
      }
      if (levels_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Levels);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Change != global::SAIC.Valkyrie.Api.V1.SystemChangeType.ChangeTypeUnknown) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Change);
      }
      if (levels_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Levels);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SystemLevelsSubscriptionResponse other) {
      if (other == null) {
        return;
      }
      if (other.Change != global::SAIC.Valkyrie.Api.V1.SystemChangeType.ChangeTypeUnknown) {
        Change = other.Change;
      }
      if (other.levels_ != null) {
        if (levels_ == null) {
          Levels = new global::SAIC.Valkyrie.Api.V1.SystemLevelsInfo();
        }
        Levels.MergeFrom(other.Levels);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Change = (global::SAIC.Valkyrie.Api.V1.SystemChangeType) input.ReadEnum();
            break;
          }
          case 18: {
            if (levels_ == null) {
              Levels = new global::SAIC.Valkyrie.Api.V1.SystemLevelsInfo();
            }
            input.ReadMessage(Levels);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Change = (global::SAIC.Valkyrie.Api.V1.SystemChangeType) input.ReadEnum();
            break;
          }
          case 18: {
            if (levels_ == null) {
              Levels = new global::SAIC.Valkyrie.Api.V1.SystemLevelsInfo();
            }
            input.ReadMessage(Levels);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ///
  /// The SystemLevelsInfo message defines the current operating levels of the system.
  /// </summary>
  public sealed partial class SystemLevelsInfo : pb::IMessage<SystemLevelsInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SystemLevelsInfo> _parser = new pb::MessageParser<SystemLevelsInfo>(() => new SystemLevelsInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SystemLevelsInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SAIC.Valkyrie.Api.V1.ConfigurationManagerReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SystemLevelsInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SystemLevelsInfo(SystemLevelsInfo other) : this() {
      level_ = other.level_;
      classification_ = other.classification_;
      systemSupportsFPConLevel_ = other.systemSupportsFPConLevel_;
      systemSupportsClassification_ = other.systemSupportsClassification_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SystemLevelsInfo Clone() {
      return new SystemLevelsInfo(this);
    }

    /// <summary>Field number for the "level" field.</summary>
    public const int LevelFieldNumber = 1;
    private global::SAIC.Valkyrie.Api.V1.FPCONLevel level_ = global::SAIC.Valkyrie.Api.V1.FPCONLevel.Unknown;
    /// <summary>
    /// current FPCON operating level
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::SAIC.Valkyrie.Api.V1.FPCONLevel Level {
      get { return level_; }
      set {
        level_ = value;
      }
    }

    /// <summary>Field number for the "classification" field.</summary>
    public const int ClassificationFieldNumber = 2;
    private global::SAIC.Valkyrie.Api.V1.ClassificationLevel classification_ = global::SAIC.Valkyrie.Api.V1.ClassificationLevel.ClassificationUnknown;
    /// <summary>
    /// current classification level
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::SAIC.Valkyrie.Api.V1.ClassificationLevel Classification {
      get { return classification_; }
      set {
        classification_ = value;
      }
    }

    /// <summary>Field number for the "systemSupportsFPConLevel" field.</summary>
    public const int SystemSupportsFPConLevelFieldNumber = 3;
    private bool systemSupportsFPConLevel_;
    /// <summary>
    /// if this installation/system uses a FPCON level or not
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool SystemSupportsFPConLevel {
      get { return systemSupportsFPConLevel_; }
      set {
        systemSupportsFPConLevel_ = value;
      }
    }

    /// <summary>Field number for the "systemSupportsClassification" field.</summary>
    public const int SystemSupportsClassificationFieldNumber = 4;
    private bool systemSupportsClassification_;
    /// <summary>
    /// if this installation/system uses a classification level or not
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool SystemSupportsClassification {
      get { return systemSupportsClassification_; }
      set {
        systemSupportsClassification_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SystemLevelsInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SystemLevelsInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Level != other.Level) return false;
      if (Classification != other.Classification) return false;
      if (SystemSupportsFPConLevel != other.SystemSupportsFPConLevel) return false;
      if (SystemSupportsClassification != other.SystemSupportsClassification) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Level != global::SAIC.Valkyrie.Api.V1.FPCONLevel.Unknown) hash ^= Level.GetHashCode();
      if (Classification != global::SAIC.Valkyrie.Api.V1.ClassificationLevel.ClassificationUnknown) hash ^= Classification.GetHashCode();
      if (SystemSupportsFPConLevel != false) hash ^= SystemSupportsFPConLevel.GetHashCode();
      if (SystemSupportsClassification != false) hash ^= SystemSupportsClassification.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Level != global::SAIC.Valkyrie.Api.V1.FPCONLevel.Unknown) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Level);
      }
      if (Classification != global::SAIC.Valkyrie.Api.V1.ClassificationLevel.ClassificationUnknown) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Classification);
      }
      if (SystemSupportsFPConLevel != false) {
        output.WriteRawTag(24);
        output.WriteBool(SystemSupportsFPConLevel);
      }
      if (SystemSupportsClassification != false) {
        output.WriteRawTag(32);
        output.WriteBool(SystemSupportsClassification);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Level != global::SAIC.Valkyrie.Api.V1.FPCONLevel.Unknown) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Level);
      }
      if (Classification != global::SAIC.Valkyrie.Api.V1.ClassificationLevel.ClassificationUnknown) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Classification);
      }
      if (SystemSupportsFPConLevel != false) {
        output.WriteRawTag(24);
        output.WriteBool(SystemSupportsFPConLevel);
      }
      if (SystemSupportsClassification != false) {
        output.WriteRawTag(32);
        output.WriteBool(SystemSupportsClassification);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Level != global::SAIC.Valkyrie.Api.V1.FPCONLevel.Unknown) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Level);
      }
      if (Classification != global::SAIC.Valkyrie.Api.V1.ClassificationLevel.ClassificationUnknown) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Classification);
      }
      if (SystemSupportsFPConLevel != false) {
        size += 1 + 1;
      }
      if (SystemSupportsClassification != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SystemLevelsInfo other) {
      if (other == null) {
        return;
      }
      if (other.Level != global::SAIC.Valkyrie.Api.V1.FPCONLevel.Unknown) {
        Level = other.Level;
      }
      if (other.Classification != global::SAIC.Valkyrie.Api.V1.ClassificationLevel.ClassificationUnknown) {
        Classification = other.Classification;
      }
      if (other.SystemSupportsFPConLevel != false) {
        SystemSupportsFPConLevel = other.SystemSupportsFPConLevel;
      }
      if (other.SystemSupportsClassification != false) {
        SystemSupportsClassification = other.SystemSupportsClassification;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Level = (global::SAIC.Valkyrie.Api.V1.FPCONLevel) input.ReadEnum();
            break;
          }
          case 16: {
            Classification = (global::SAIC.Valkyrie.Api.V1.ClassificationLevel) input.ReadEnum();
            break;
          }
          case 24: {
            SystemSupportsFPConLevel = input.ReadBool();
            break;
          }
          case 32: {
            SystemSupportsClassification = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Level = (global::SAIC.Valkyrie.Api.V1.FPCONLevel) input.ReadEnum();
            break;
          }
          case 16: {
            Classification = (global::SAIC.Valkyrie.Api.V1.ClassificationLevel) input.ReadEnum();
            break;
          }
          case 24: {
            SystemSupportsFPConLevel = input.ReadBool();
            break;
          }
          case 32: {
            SystemSupportsClassification = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ///
  /// The ServicesConfigurationResponse message contains the details of all running services at a Valkyrie
  /// installation. This is the response from the {@link getSdkServicesConfig} call.
  /// </summary>
  public sealed partial class ServicesConfigurationResponse : pb::IMessage<ServicesConfigurationResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ServicesConfigurationResponse> _parser = new pb::MessageParser<ServicesConfigurationResponse>(() => new ServicesConfigurationResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ServicesConfigurationResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SAIC.Valkyrie.Api.V1.ConfigurationManagerReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ServicesConfigurationResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ServicesConfigurationResponse(ServicesConfigurationResponse other) : this() {
      services_ = other.services_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ServicesConfigurationResponse Clone() {
      return new ServicesConfigurationResponse(this);
    }

    /// <summary>Field number for the "services" field.</summary>
    public const int ServicesFieldNumber = 1;
    private static readonly pb::FieldCodec<global::SAIC.Valkyrie.Api.V1.ServiceConfiguration> _repeated_services_codec
        = pb::FieldCodec.ForMessage(10, global::SAIC.Valkyrie.Api.V1.ServiceConfiguration.Parser);
    private readonly pbc::RepeatedField<global::SAIC.Valkyrie.Api.V1.ServiceConfiguration> services_ = new pbc::RepeatedField<global::SAIC.Valkyrie.Api.V1.ServiceConfiguration>();
    /// <summary>
    /// List of SDK service configurations
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::SAIC.Valkyrie.Api.V1.ServiceConfiguration> Services {
      get { return services_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ServicesConfigurationResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ServicesConfigurationResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!services_.Equals(other.services_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= services_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      services_.WriteTo(output, _repeated_services_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      services_.WriteTo(ref output, _repeated_services_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += services_.CalculateSize(_repeated_services_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ServicesConfigurationResponse other) {
      if (other == null) {
        return;
      }
      services_.Add(other.services_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            services_.AddEntriesFrom(input, _repeated_services_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            services_.AddEntriesFrom(ref input, _repeated_services_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
