// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ServiceStatus.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace SAIC.Valkyrie.Api.V1 {

  /// <summary>Holder for reflection information generated from ServiceStatus.proto</summary>
  public static partial class ServiceStatusReflection {

    #region Descriptor
    /// <summary>File descriptor for ServiceStatus.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ServiceStatusReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChNTZXJ2aWNlU3RhdHVzLnByb3RvEhtzYWljLnZhbGt5cmllLnNkay5nZW5l",
            "cmF0ZWQaDENvbW1vbi5wcm90byJ2ChJTZXJ2aWNlV2FybmluZ0luZm8SSAoL",
            "d2FybmluZ1R5cGUYASABKA4yMy5zYWljLnZhbGt5cmllLnNkay5nZW5lcmF0",
            "ZWQuU2VydmljZVdhcm5pbmdUeXBlRW51bRIWCg53YXJuaW5nTWVzc2FnZRgC",
            "IAEoCSJ4ChNUcmFuc3BvcnRTdGF0dXNJbmZvEgwKBG5hbWUYAiABKAkSPgoG",
            "c3RhdHVzGAMgASgOMi4uc2FpYy52YWxreXJpZS5zZGsuZ2VuZXJhdGVkLk9w",
            "ZXJhdGlvbmFsU3RhdHVzEg0KBWVycm9yGAQgASgJSgQIARACInIKG1NlcnZp",
            "Y2VTdWJzY3JpcHRpb25SZXNwb25zZRIRCgl0aW1lc3RhbXAYASABKAMSQAoI",
            "c3RhdHVzZXMYAiADKAsyLi5zYWljLnZhbGt5cmllLnNkay5nZW5lcmF0ZWQu",
            "U2VydmljZVN0YXR1c0luZm8i7AIKEVNlcnZpY2VTdGF0dXNJbmZvEhEKCXRp",
            "bWVzdGFtcBgBIAEoAxITCgtzZXJ2aWNlTmFtZRgCIAEoCRJBCgtzZXJ2aWNl",
            "VHlwZRgDIAEoDjIsLnNhaWMudmFsa3lyaWUuc2RrLmdlbmVyYXRlZC5TZXJ2",
            "aWNlVHlwZUVudW0SPgoGc3RhdHVzGAQgASgOMi4uc2FpYy52YWxreXJpZS5z",
            "ZGsuZ2VuZXJhdGVkLk9wZXJhdGlvbmFsU3RhdHVzEg0KBWJ1aWxkGAUgASgJ",
            "EhQKDGlzUmVnaXN0ZXJlZBgGIAEoCBJBCgh3YXJuaW5ncxgHIAMoCzIvLnNh",
            "aWMudmFsa3lyaWUuc2RrLmdlbmVyYXRlZC5TZXJ2aWNlV2FybmluZ0luZm8S",
            "RAoKdHJhbnNwb3J0cxgIIAMoCzIwLnNhaWMudmFsa3lyaWUuc2RrLmdlbmVy",
            "YXRlZC5UcmFuc3BvcnRTdGF0dXNJbmZvKsUBChZTZXJ2aWNlV2FybmluZ1R5",
            "cGVFbnVtEhsKF1NFUlZJQ0VfV0FSTklOR19VTktOT1dOEAASIwofU0VSVklD",
            "RV9XQVJOSU5HX05FVkVSX0NPTk5FQ1RFRBABEicKI1NFUlZJQ0VfV0FSTklO",
            "R19DT05GSUdVUkFUSU9OX0VSUk9SEAISIwofU0VSVklDRV9XQVJOSU5HX1RS",
            "QU5TUE9SVF9FUlJPUhADEhsKF1NFUlZJQ0VfV0FSTklOR19HRU5FUkFMEAQq",
            "cgoPU2VydmljZVR5cGVFbnVtEhgKFFNFUlZJQ0VfVFlQRV9VTktOT1dOEAAS",
            "FAoQU0VSVklDRV9UWVBFX0RPThABEhQKEFNFUlZJQ0VfVFlQRV9TREsQAhIZ",
            "ChVTRVJWSUNFX1RZUEVfRVhURVJOQUwQA0JuChtzYWljLnZhbGt5cmllLnNk",
            "ay5nZW5lcmF0ZWRCElNlcnZpY2VTdGF0dXNQcm90b1okZ2l0aHViLmNvbS90",
            "bWhvbHQvR2VuRG9jUHJvdG8vc2RrL2dvqgIUU0FJQy5WYWxreXJpZS5BcGku",
            "VjFiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::SAIC.Valkyrie.Api.V1.CommonReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::SAIC.Valkyrie.Api.V1.ServiceWarningTypeEnum), typeof(global::SAIC.Valkyrie.Api.V1.ServiceTypeEnum), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::SAIC.Valkyrie.Api.V1.ServiceWarningInfo), global::SAIC.Valkyrie.Api.V1.ServiceWarningInfo.Parser, new[]{ "WarningType", "WarningMessage" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::SAIC.Valkyrie.Api.V1.TransportStatusInfo), global::SAIC.Valkyrie.Api.V1.TransportStatusInfo.Parser, new[]{ "Name", "Status", "Error" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::SAIC.Valkyrie.Api.V1.ServiceSubscriptionResponse), global::SAIC.Valkyrie.Api.V1.ServiceSubscriptionResponse.Parser, new[]{ "Timestamp", "Statuses" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::SAIC.Valkyrie.Api.V1.ServiceStatusInfo), global::SAIC.Valkyrie.Api.V1.ServiceStatusInfo.Parser, new[]{ "Timestamp", "ServiceName", "ServiceType", "Status", "Build", "IsRegistered", "Warnings", "Transports" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  ///
  /// The ServiceWarningTypeEnum enumeration contains possible service warning message types.
  /// </summary>
  public enum ServiceWarningTypeEnum {
    [pbr::OriginalName("SERVICE_WARNING_UNKNOWN")] ServiceWarningUnknown = 0,
    [pbr::OriginalName("SERVICE_WARNING_NEVER_CONNECTED")] ServiceWarningNeverConnected = 1,
    [pbr::OriginalName("SERVICE_WARNING_CONFIGURATION_ERROR")] ServiceWarningConfigurationError = 2,
    [pbr::OriginalName("SERVICE_WARNING_TRANSPORT_ERROR")] ServiceWarningTransportError = 3,
    [pbr::OriginalName("SERVICE_WARNING_GENERAL")] ServiceWarningGeneral = 4,
  }

  /// <summary>
  ///
  /// The ServiceTypeEnum enumeration is used for service-status;
  /// answers the question: what kind of service is this?
  /// </summary>
  public enum ServiceTypeEnum {
    [pbr::OriginalName("SERVICE_TYPE_UNKNOWN")] ServiceTypeUnknown = 0,
    [pbr::OriginalName("SERVICE_TYPE_DON")] ServiceTypeDon = 1,
    [pbr::OriginalName("SERVICE_TYPE_SDK")] ServiceTypeSdk = 2,
    [pbr::OriginalName("SERVICE_TYPE_EXTERNAL")] ServiceTypeExternal = 3,
  }

  #endregion

  #region Messages
  /// <summary>
  ///
  /// The ServiceWarningInfo message contains details for one warning message from a service,
  /// delivered within its status.
  /// </summary>
  public sealed partial class ServiceWarningInfo : pb::IMessage<ServiceWarningInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ServiceWarningInfo> _parser = new pb::MessageParser<ServiceWarningInfo>(() => new ServiceWarningInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ServiceWarningInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SAIC.Valkyrie.Api.V1.ServiceStatusReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ServiceWarningInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ServiceWarningInfo(ServiceWarningInfo other) : this() {
      warningType_ = other.warningType_;
      warningMessage_ = other.warningMessage_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ServiceWarningInfo Clone() {
      return new ServiceWarningInfo(this);
    }

    /// <summary>Field number for the "warningType" field.</summary>
    public const int WarningTypeFieldNumber = 1;
    private global::SAIC.Valkyrie.Api.V1.ServiceWarningTypeEnum warningType_ = global::SAIC.Valkyrie.Api.V1.ServiceWarningTypeEnum.ServiceWarningUnknown;
    /// <summary>
    /// The type of warning
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::SAIC.Valkyrie.Api.V1.ServiceWarningTypeEnum WarningType {
      get { return warningType_; }
      set {
        warningType_ = value;
      }
    }

    /// <summary>Field number for the "warningMessage" field.</summary>
    public const int WarningMessageFieldNumber = 2;
    private string warningMessage_ = "";
    /// <summary>
    /// User-friendly warning message to display and indicate the problem
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string WarningMessage {
      get { return warningMessage_; }
      set {
        warningMessage_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ServiceWarningInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ServiceWarningInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (WarningType != other.WarningType) return false;
      if (WarningMessage != other.WarningMessage) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (WarningType != global::SAIC.Valkyrie.Api.V1.ServiceWarningTypeEnum.ServiceWarningUnknown) hash ^= WarningType.GetHashCode();
      if (WarningMessage.Length != 0) hash ^= WarningMessage.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (WarningType != global::SAIC.Valkyrie.Api.V1.ServiceWarningTypeEnum.ServiceWarningUnknown) {
        output.WriteRawTag(8);
        output.WriteEnum((int) WarningType);
      }
      if (WarningMessage.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(WarningMessage);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (WarningType != global::SAIC.Valkyrie.Api.V1.ServiceWarningTypeEnum.ServiceWarningUnknown) {
        output.WriteRawTag(8);
        output.WriteEnum((int) WarningType);
      }
      if (WarningMessage.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(WarningMessage);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (WarningType != global::SAIC.Valkyrie.Api.V1.ServiceWarningTypeEnum.ServiceWarningUnknown) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) WarningType);
      }
      if (WarningMessage.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(WarningMessage);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ServiceWarningInfo other) {
      if (other == null) {
        return;
      }
      if (other.WarningType != global::SAIC.Valkyrie.Api.V1.ServiceWarningTypeEnum.ServiceWarningUnknown) {
        WarningType = other.WarningType;
      }
      if (other.WarningMessage.Length != 0) {
        WarningMessage = other.WarningMessage;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            WarningType = (global::SAIC.Valkyrie.Api.V1.ServiceWarningTypeEnum) input.ReadEnum();
            break;
          }
          case 18: {
            WarningMessage = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            WarningType = (global::SAIC.Valkyrie.Api.V1.ServiceWarningTypeEnum) input.ReadEnum();
            break;
          }
          case 18: {
            WarningMessage = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ///
  /// The TransportStatusInfo message contains status information for one transport
  /// being managed by a service.
  /// </summary>
  public sealed partial class TransportStatusInfo : pb::IMessage<TransportStatusInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TransportStatusInfo> _parser = new pb::MessageParser<TransportStatusInfo>(() => new TransportStatusInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TransportStatusInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SAIC.Valkyrie.Api.V1.ServiceStatusReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TransportStatusInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TransportStatusInfo(TransportStatusInfo other) : this() {
      name_ = other.name_;
      status_ = other.status_;
      error_ = other.error_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TransportStatusInfo Clone() {
      return new TransportStatusInfo(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 2;
    private string name_ = "";
    /// <summary>
    /// a friendly name for this transport (optional)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "status" field.</summary>
    public const int StatusFieldNumber = 3;
    private global::SAIC.Valkyrie.Api.V1.OperationalStatus status_ = global::SAIC.Valkyrie.Api.V1.OperationalStatus.StatusUnknown;
    /// <summary>
    /// transport connection status
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::SAIC.Valkyrie.Api.V1.OperationalStatus Status {
      get { return status_; }
      set {
        status_ = value;
      }
    }

    /// <summary>Field number for the "error" field.</summary>
    public const int ErrorFieldNumber = 4;
    private string error_ = "";
    /// <summary>
    /// error message if not operational
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Error {
      get { return error_; }
      set {
        error_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TransportStatusInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TransportStatusInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if (Status != other.Status) return false;
      if (Error != other.Error) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Status != global::SAIC.Valkyrie.Api.V1.OperationalStatus.StatusUnknown) hash ^= Status.GetHashCode();
      if (Error.Length != 0) hash ^= Error.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Name.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (Status != global::SAIC.Valkyrie.Api.V1.OperationalStatus.StatusUnknown) {
        output.WriteRawTag(24);
        output.WriteEnum((int) Status);
      }
      if (Error.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Error);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Name.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (Status != global::SAIC.Valkyrie.Api.V1.OperationalStatus.StatusUnknown) {
        output.WriteRawTag(24);
        output.WriteEnum((int) Status);
      }
      if (Error.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Error);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Status != global::SAIC.Valkyrie.Api.V1.OperationalStatus.StatusUnknown) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Status);
      }
      if (Error.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Error);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TransportStatusInfo other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Status != global::SAIC.Valkyrie.Api.V1.OperationalStatus.StatusUnknown) {
        Status = other.Status;
      }
      if (other.Error.Length != 0) {
        Error = other.Error;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 24: {
            Status = (global::SAIC.Valkyrie.Api.V1.OperationalStatus) input.ReadEnum();
            break;
          }
          case 34: {
            Error = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 24: {
            Status = (global::SAIC.Valkyrie.Api.V1.OperationalStatus) input.ReadEnum();
            break;
          }
          case 34: {
            Error = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ///
  /// The ServiceSubscriptionResponse message is what is sent back to a subscribed client.
  /// Rather than sending a stream of ServiceStatusInfo values back, we send 1 large message periodically.
  /// This is both more efficient and defines one "set" of service statuses. Otherwise it would be difficult to
  /// determine one complete set of service status values.
  /// </summary>
  public sealed partial class ServiceSubscriptionResponse : pb::IMessage<ServiceSubscriptionResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ServiceSubscriptionResponse> _parser = new pb::MessageParser<ServiceSubscriptionResponse>(() => new ServiceSubscriptionResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ServiceSubscriptionResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SAIC.Valkyrie.Api.V1.ServiceStatusReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ServiceSubscriptionResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ServiceSubscriptionResponse(ServiceSubscriptionResponse other) : this() {
      timestamp_ = other.timestamp_;
      statuses_ = other.statuses_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ServiceSubscriptionResponse Clone() {
      return new ServiceSubscriptionResponse(this);
    }

    /// <summary>Field number for the "timestamp" field.</summary>
    public const int TimestampFieldNumber = 1;
    private long timestamp_;
    /// <summary>
    /// publish timestamp (milliseconds since epoch)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Timestamp {
      get { return timestamp_; }
      set {
        timestamp_ = value;
      }
    }

    /// <summary>Field number for the "statuses" field.</summary>
    public const int StatusesFieldNumber = 2;
    private static readonly pb::FieldCodec<global::SAIC.Valkyrie.Api.V1.ServiceStatusInfo> _repeated_statuses_codec
        = pb::FieldCodec.ForMessage(18, global::SAIC.Valkyrie.Api.V1.ServiceStatusInfo.Parser);
    private readonly pbc::RepeatedField<global::SAIC.Valkyrie.Api.V1.ServiceStatusInfo> statuses_ = new pbc::RepeatedField<global::SAIC.Valkyrie.Api.V1.ServiceStatusInfo>();
    /// <summary>
    /// set of service statuses within Valkyrie
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::SAIC.Valkyrie.Api.V1.ServiceStatusInfo> Statuses {
      get { return statuses_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ServiceSubscriptionResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ServiceSubscriptionResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Timestamp != other.Timestamp) return false;
      if(!statuses_.Equals(other.statuses_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Timestamp != 0L) hash ^= Timestamp.GetHashCode();
      hash ^= statuses_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Timestamp != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Timestamp);
      }
      statuses_.WriteTo(output, _repeated_statuses_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Timestamp != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Timestamp);
      }
      statuses_.WriteTo(ref output, _repeated_statuses_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Timestamp != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Timestamp);
      }
      size += statuses_.CalculateSize(_repeated_statuses_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ServiceSubscriptionResponse other) {
      if (other == null) {
        return;
      }
      if (other.Timestamp != 0L) {
        Timestamp = other.Timestamp;
      }
      statuses_.Add(other.statuses_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Timestamp = input.ReadInt64();
            break;
          }
          case 18: {
            statuses_.AddEntriesFrom(input, _repeated_statuses_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Timestamp = input.ReadInt64();
            break;
          }
          case 18: {
            statuses_.AddEntriesFrom(ref input, _repeated_statuses_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ///
  /// The ServiceStatusInfo message contains details for one service status.
  /// </summary>
  public sealed partial class ServiceStatusInfo : pb::IMessage<ServiceStatusInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ServiceStatusInfo> _parser = new pb::MessageParser<ServiceStatusInfo>(() => new ServiceStatusInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ServiceStatusInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SAIC.Valkyrie.Api.V1.ServiceStatusReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ServiceStatusInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ServiceStatusInfo(ServiceStatusInfo other) : this() {
      timestamp_ = other.timestamp_;
      serviceName_ = other.serviceName_;
      serviceType_ = other.serviceType_;
      status_ = other.status_;
      build_ = other.build_;
      isRegistered_ = other.isRegistered_;
      warnings_ = other.warnings_.Clone();
      transports_ = other.transports_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ServiceStatusInfo Clone() {
      return new ServiceStatusInfo(this);
    }

    /// <summary>Field number for the "timestamp" field.</summary>
    public const int TimestampFieldNumber = 1;
    private long timestamp_;
    /// <summary>
    /// status update timestamp (milliseconds since epoch)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Timestamp {
      get { return timestamp_; }
      set {
        timestamp_ = value;
      }
    }

    /// <summary>Field number for the "serviceName" field.</summary>
    public const int ServiceNameFieldNumber = 2;
    private string serviceName_ = "";
    /// <summary>
    /// name of this service
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ServiceName {
      get { return serviceName_; }
      set {
        serviceName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "serviceType" field.</summary>
    public const int ServiceTypeFieldNumber = 3;
    private global::SAIC.Valkyrie.Api.V1.ServiceTypeEnum serviceType_ = global::SAIC.Valkyrie.Api.V1.ServiceTypeEnum.ServiceTypeUnknown;
    /// <summary>
    /// what kind of service this is
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::SAIC.Valkyrie.Api.V1.ServiceTypeEnum ServiceType {
      get { return serviceType_; }
      set {
        serviceType_ = value;
      }
    }

    /// <summary>Field number for the "status" field.</summary>
    public const int StatusFieldNumber = 4;
    private global::SAIC.Valkyrie.Api.V1.OperationalStatus status_ = global::SAIC.Valkyrie.Api.V1.OperationalStatus.StatusUnknown;
    /// <summary>
    /// operational status for this service
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::SAIC.Valkyrie.Api.V1.OperationalStatus Status {
      get { return status_; }
      set {
        status_ = value;
      }
    }

    /// <summary>Field number for the "build" field.</summary>
    public const int BuildFieldNumber = 5;
    private string build_ = "";
    /// <summary>
    /// build / version information for this service
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Build {
      get { return build_; }
      set {
        build_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "isRegistered" field.</summary>
    public const int IsRegisteredFieldNumber = 6;
    private bool isRegistered_;
    /// <summary>
    /// if the service has been registered into the system. kind of DON specific.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsRegistered {
      get { return isRegistered_; }
      set {
        isRegistered_ = value;
      }
    }

    /// <summary>Field number for the "warnings" field.</summary>
    public const int WarningsFieldNumber = 7;
    private static readonly pb::FieldCodec<global::SAIC.Valkyrie.Api.V1.ServiceWarningInfo> _repeated_warnings_codec
        = pb::FieldCodec.ForMessage(58, global::SAIC.Valkyrie.Api.V1.ServiceWarningInfo.Parser);
    private readonly pbc::RepeatedField<global::SAIC.Valkyrie.Api.V1.ServiceWarningInfo> warnings_ = new pbc::RepeatedField<global::SAIC.Valkyrie.Api.V1.ServiceWarningInfo>();
    /// <summary>
    /// warning messages from the service
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::SAIC.Valkyrie.Api.V1.ServiceWarningInfo> Warnings {
      get { return warnings_; }
    }

    /// <summary>Field number for the "transports" field.</summary>
    public const int TransportsFieldNumber = 8;
    private static readonly pb::FieldCodec<global::SAIC.Valkyrie.Api.V1.TransportStatusInfo> _repeated_transports_codec
        = pb::FieldCodec.ForMessage(66, global::SAIC.Valkyrie.Api.V1.TransportStatusInfo.Parser);
    private readonly pbc::RepeatedField<global::SAIC.Valkyrie.Api.V1.TransportStatusInfo> transports_ = new pbc::RepeatedField<global::SAIC.Valkyrie.Api.V1.TransportStatusInfo>();
    /// <summary>
    /// status for the transports being maintained by this service
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::SAIC.Valkyrie.Api.V1.TransportStatusInfo> Transports {
      get { return transports_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ServiceStatusInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ServiceStatusInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Timestamp != other.Timestamp) return false;
      if (ServiceName != other.ServiceName) return false;
      if (ServiceType != other.ServiceType) return false;
      if (Status != other.Status) return false;
      if (Build != other.Build) return false;
      if (IsRegistered != other.IsRegistered) return false;
      if(!warnings_.Equals(other.warnings_)) return false;
      if(!transports_.Equals(other.transports_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Timestamp != 0L) hash ^= Timestamp.GetHashCode();
      if (ServiceName.Length != 0) hash ^= ServiceName.GetHashCode();
      if (ServiceType != global::SAIC.Valkyrie.Api.V1.ServiceTypeEnum.ServiceTypeUnknown) hash ^= ServiceType.GetHashCode();
      if (Status != global::SAIC.Valkyrie.Api.V1.OperationalStatus.StatusUnknown) hash ^= Status.GetHashCode();
      if (Build.Length != 0) hash ^= Build.GetHashCode();
      if (IsRegistered != false) hash ^= IsRegistered.GetHashCode();
      hash ^= warnings_.GetHashCode();
      hash ^= transports_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Timestamp != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Timestamp);
      }
      if (ServiceName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ServiceName);
      }
      if (ServiceType != global::SAIC.Valkyrie.Api.V1.ServiceTypeEnum.ServiceTypeUnknown) {
        output.WriteRawTag(24);
        output.WriteEnum((int) ServiceType);
      }
      if (Status != global::SAIC.Valkyrie.Api.V1.OperationalStatus.StatusUnknown) {
        output.WriteRawTag(32);
        output.WriteEnum((int) Status);
      }
      if (Build.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Build);
      }
      if (IsRegistered != false) {
        output.WriteRawTag(48);
        output.WriteBool(IsRegistered);
      }
      warnings_.WriteTo(output, _repeated_warnings_codec);
      transports_.WriteTo(output, _repeated_transports_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Timestamp != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Timestamp);
      }
      if (ServiceName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ServiceName);
      }
      if (ServiceType != global::SAIC.Valkyrie.Api.V1.ServiceTypeEnum.ServiceTypeUnknown) {
        output.WriteRawTag(24);
        output.WriteEnum((int) ServiceType);
      }
      if (Status != global::SAIC.Valkyrie.Api.V1.OperationalStatus.StatusUnknown) {
        output.WriteRawTag(32);
        output.WriteEnum((int) Status);
      }
      if (Build.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Build);
      }
      if (IsRegistered != false) {
        output.WriteRawTag(48);
        output.WriteBool(IsRegistered);
      }
      warnings_.WriteTo(ref output, _repeated_warnings_codec);
      transports_.WriteTo(ref output, _repeated_transports_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Timestamp != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Timestamp);
      }
      if (ServiceName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ServiceName);
      }
      if (ServiceType != global::SAIC.Valkyrie.Api.V1.ServiceTypeEnum.ServiceTypeUnknown) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ServiceType);
      }
      if (Status != global::SAIC.Valkyrie.Api.V1.OperationalStatus.StatusUnknown) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Status);
      }
      if (Build.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Build);
      }
      if (IsRegistered != false) {
        size += 1 + 1;
      }
      size += warnings_.CalculateSize(_repeated_warnings_codec);
      size += transports_.CalculateSize(_repeated_transports_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ServiceStatusInfo other) {
      if (other == null) {
        return;
      }
      if (other.Timestamp != 0L) {
        Timestamp = other.Timestamp;
      }
      if (other.ServiceName.Length != 0) {
        ServiceName = other.ServiceName;
      }
      if (other.ServiceType != global::SAIC.Valkyrie.Api.V1.ServiceTypeEnum.ServiceTypeUnknown) {
        ServiceType = other.ServiceType;
      }
      if (other.Status != global::SAIC.Valkyrie.Api.V1.OperationalStatus.StatusUnknown) {
        Status = other.Status;
      }
      if (other.Build.Length != 0) {
        Build = other.Build;
      }
      if (other.IsRegistered != false) {
        IsRegistered = other.IsRegistered;
      }
      warnings_.Add(other.warnings_);
      transports_.Add(other.transports_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Timestamp = input.ReadInt64();
            break;
          }
          case 18: {
            ServiceName = input.ReadString();
            break;
          }
          case 24: {
            ServiceType = (global::SAIC.Valkyrie.Api.V1.ServiceTypeEnum) input.ReadEnum();
            break;
          }
          case 32: {
            Status = (global::SAIC.Valkyrie.Api.V1.OperationalStatus) input.ReadEnum();
            break;
          }
          case 42: {
            Build = input.ReadString();
            break;
          }
          case 48: {
            IsRegistered = input.ReadBool();
            break;
          }
          case 58: {
            warnings_.AddEntriesFrom(input, _repeated_warnings_codec);
            break;
          }
          case 66: {
            transports_.AddEntriesFrom(input, _repeated_transports_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Timestamp = input.ReadInt64();
            break;
          }
          case 18: {
            ServiceName = input.ReadString();
            break;
          }
          case 24: {
            ServiceType = (global::SAIC.Valkyrie.Api.V1.ServiceTypeEnum) input.ReadEnum();
            break;
          }
          case 32: {
            Status = (global::SAIC.Valkyrie.Api.V1.OperationalStatus) input.ReadEnum();
            break;
          }
          case 42: {
            Build = input.ReadString();
            break;
          }
          case 48: {
            IsRegistered = input.ReadBool();
            break;
          }
          case 58: {
            warnings_.AddEntriesFrom(ref input, _repeated_warnings_codec);
            break;
          }
          case 66: {
            transports_.AddEntriesFrom(ref input, _repeated_transports_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
