// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: SystemsManager.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace SAIC.Valkyrie.Api.V1 {

  /// <summary>Holder for reflection information generated from SystemsManager.proto</summary>
  public static partial class SystemsManagerReflection {

    #region Descriptor
    /// <summary>File descriptor for SystemsManager.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SystemsManagerReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChRTeXN0ZW1zTWFuYWdlci5wcm90bxIbc2FpYy52YWxreXJpZS5zZGsuZ2Vu",
            "ZXJhdGVkGhtnb29nbGUvcHJvdG9idWYvZW1wdHkucHJvdG8aDENvbW1vbi5w",
            "cm90bxoTU2VydmljZVN0YXR1cy5wcm90byJqChlDbGllbnRTeXN0ZW1zU3Vi",
            "c2NyaXB0aW9uEhAKCHNlcnZpY2VzGAEgAygJEjsKBXR5cGVzGAIgAygOMiwu",
            "c2FpYy52YWxreXJpZS5zZGsuZ2VuZXJhdGVkLlNlcnZpY2VUeXBlRW51bTKo",
            "AwoOU3lzdGVtc01hbmFnZXISTgoKZ2V0VmVyc2lvbhIWLmdvb2dsZS5wcm90",
            "b2J1Zi5FbXB0eRooLnNhaWMudmFsa3lyaWUuc2RrLmdlbmVyYXRlZC5WZXJz",
            "aW9uSW5mbxJfCgtnZXRTdGF0dXNlcxIWLmdvb2dsZS5wcm90b2J1Zi5FbXB0",
            "eRo4LnNhaWMudmFsa3lyaWUuc2RrLmdlbmVyYXRlZC5TZXJ2aWNlU3Vic2Ny",
            "aXB0aW9uUmVzcG9uc2USZAoHcHVibGlzaBIuLnNhaWMudmFsa3lyaWUuc2Rr",
            "LmdlbmVyYXRlZC5TZXJ2aWNlU3RhdHVzSW5mbxopLnNhaWMudmFsa3lyaWUu",
            "c2RrLmdlbmVyYXRlZC5SZXNwb25zZUluZm8SfwoJc3Vic2NyaWJlEjYuc2Fp",
            "Yy52YWxreXJpZS5zZGsuZ2VuZXJhdGVkLkNsaWVudFN5c3RlbXNTdWJzY3Jp",
            "cHRpb24aOC5zYWljLnZhbGt5cmllLnNkay5nZW5lcmF0ZWQuU2VydmljZVN1",
            "YnNjcmlwdGlvblJlc3BvbnNlMAFCbwobc2FpYy52YWxreXJpZS5zZGsuZ2Vu",
            "ZXJhdGVkQhNTeXN0ZW1zTWFuYWdlclByb3RvWiRnaXRodWIuY29tL3RtaG9s",
            "dC9HZW5Eb2NQcm90by9zZGsvZ2+qAhRTQUlDLlZhbGt5cmllLkFwaS5WMWIG",
            "cHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, global::SAIC.Valkyrie.Api.V1.CommonReflection.Descriptor, global::SAIC.Valkyrie.Api.V1.ServiceStatusReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::SAIC.Valkyrie.Api.V1.ClientSystemsSubscription), global::SAIC.Valkyrie.Api.V1.ClientSystemsSubscription.Parser, new[]{ "Services", "Types_" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  ///
  /// The ClientSystemSubscription message contains inbound subscription details for this client.
  /// This provides the ability to subscribe to a constrained set of event types for system services.
  /// </summary>
  public sealed partial class ClientSystemsSubscription : pb::IMessage<ClientSystemsSubscription>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ClientSystemsSubscription> _parser = new pb::MessageParser<ClientSystemsSubscription>(() => new ClientSystemsSubscription());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ClientSystemsSubscription> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SAIC.Valkyrie.Api.V1.SystemsManagerReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ClientSystemsSubscription() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ClientSystemsSubscription(ClientSystemsSubscription other) : this() {
      services_ = other.services_.Clone();
      types_ = other.types_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ClientSystemsSubscription Clone() {
      return new ClientSystemsSubscription(this);
    }

    /// <summary>Field number for the "services" field.</summary>
    public const int ServicesFieldNumber = 1;
    private static readonly pb::FieldCodec<string> _repeated_services_codec
        = pb::FieldCodec.ForString(10);
    private readonly pbc::RepeatedField<string> services_ = new pbc::RepeatedField<string>();
    /// <summary>
    /// filtering for which service names to receive status for. if empty no filtering.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> Services {
      get { return services_; }
    }

    /// <summary>Field number for the "types" field.</summary>
    public const int Types_FieldNumber = 2;
    private static readonly pb::FieldCodec<global::SAIC.Valkyrie.Api.V1.ServiceTypeEnum> _repeated_types_codec
        = pb::FieldCodec.ForEnum(18, x => (int) x, x => (global::SAIC.Valkyrie.Api.V1.ServiceTypeEnum) x);
    private readonly pbc::RepeatedField<global::SAIC.Valkyrie.Api.V1.ServiceTypeEnum> types_ = new pbc::RepeatedField<global::SAIC.Valkyrie.Api.V1.ServiceTypeEnum>();
    /// <summary>
    /// filtering for which service types to receive status for. if empty no filtering.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::SAIC.Valkyrie.Api.V1.ServiceTypeEnum> Types_ {
      get { return types_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ClientSystemsSubscription);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ClientSystemsSubscription other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!services_.Equals(other.services_)) return false;
      if(!types_.Equals(other.types_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= services_.GetHashCode();
      hash ^= types_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      services_.WriteTo(output, _repeated_services_codec);
      types_.WriteTo(output, _repeated_types_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      services_.WriteTo(ref output, _repeated_services_codec);
      types_.WriteTo(ref output, _repeated_types_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += services_.CalculateSize(_repeated_services_codec);
      size += types_.CalculateSize(_repeated_types_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ClientSystemsSubscription other) {
      if (other == null) {
        return;
      }
      services_.Add(other.services_);
      types_.Add(other.types_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            services_.AddEntriesFrom(input, _repeated_services_codec);
            break;
          }
          case 18:
          case 16: {
            types_.AddEntriesFrom(input, _repeated_types_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            services_.AddEntriesFrom(ref input, _repeated_services_codec);
            break;
          }
          case 18:
          case 16: {
            types_.AddEntriesFrom(ref input, _repeated_types_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
