// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ThreatsManager.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace SAIC.Valkyrie.Api.V1 {

  /// <summary>Holder for reflection information generated from ThreatsManager.proto</summary>
  public static partial class ThreatsManagerReflection {

    #region Descriptor
    /// <summary>File descriptor for ThreatsManager.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ThreatsManagerReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChRUaHJlYXRzTWFuYWdlci5wcm90bxIbc2FpYy52YWxreXJpZS5zZGsuZ2Vu",
            "ZXJhdGVkGhtnb29nbGUvcHJvdG9idWYvZW1wdHkucHJvdG8aDENvbW1vbi5w",
            "cm90bxoNVGhyZWF0cy5wcm90bxoMRmlsdGVyLnByb3RvGg1IZWF0bWFwLnBy",
            "b3RvIigKFFRocmVhdERldGFpbHNSZXF1ZXN0EhAKCHRocmVhdElkGAEgAygD",
            "IlYKFVRocmVhdEFkZGl0aW9uRGV0YWlscxI3CgZ0aHJlYXQYAiABKAsyJy5z",
            "YWljLnZhbGt5cmllLnNkay5nZW5lcmF0ZWQuVGhyZWF0SW5mb0oECAEQAiLb",
            "AQoaVGhyZWF0c01hbmFnZXJTdWJzY3JpcHRpb24SHwoXc3Vic2NyaWJlVG9B",
            "ZmZpbGlhdGlvbnMYASABKAgSGgoSc3Vic2NyaWJlVG9UaHJlYXRzGAIgASgI",
            "EiAKGHN1YnNjcmliZVRvRmlsdGVyU3VtbWFyeRgDIAEoCBI6CgdmaWx0ZXJz",
            "GAQgASgLMikuc2FpYy52YWxreXJpZS5zZGsuZ2VuZXJhdGVkLkZpbHRlckNv",
            "bmZpZxIiChpzdWJzY3JpYmVUb0NsYXNzaWZpY2F0aW9ucxgFIAEoCCKkAQoY",
            "VGFyZ2V0Q2xhc3NpZmljYXRpb25JbmZvEj0KBnRhcmdldBgBIAEoCzItLnNh",
            "aWMudmFsa3lyaWUuc2RrLmdlbmVyYXRlZC5UYXJnZXRJZGVudGlmaWVyEkkK",
            "DmNsYXNzaWZpY2F0aW9uGAIgASgOMjEuc2FpYy52YWxreXJpZS5zZGsuZ2Vu",
            "ZXJhdGVkLlRhcmdldENsYXNzaWZpY2F0aW9uIoYBChxUaHJlYXRDbGFzc2lm",
            "aWNhdGlvblJlc3BvbnNlElEKEmNsYXNzaWZpY2F0aW9uSW5mbxgBIAEoCzI1",
            "LnNhaWMudmFsa3lyaWUuc2RrLmdlbmVyYXRlZC5UYXJnZXRDbGFzc2lmaWNh",
            "dGlvbkluZm8SEwoLaGFzVGltZWRPdXQYAiABKAgifQoZVGhyZWF0QWZmaWxp",
            "YXRpb25SZXNwb25zZRJLCg9hZmZpbGlhdGlvbkluZm8YASABKAsyMi5zYWlj",
            "LnZhbGt5cmllLnNkay5nZW5lcmF0ZWQuVGFyZ2V0QWZmaWxpYXRpb25JbmZv",
            "EhMKC2hhc1RpbWVkT3V0GAIgASgIIigKDUZpbHRlclN1bW1hcnkSFwoPdGhy",
            "ZWF0c0ZpbHRlcmVkGAEgASgDItACCiJUaHJlYXRzTWFuYWdlclN1YnNjcmlw",
            "dGlvblJlc3BvbnNlEjkKBnRocmVhdBgBIAEoCzInLnNhaWMudmFsa3lyaWUu",
            "c2RrLmdlbmVyYXRlZC5UaHJlYXRJbmZvSAASQwoNZmlsdGVyU3VtbWFyeRgC",
            "IAEoCzIqLnNhaWMudmFsa3lyaWUuc2RrLmdlbmVyYXRlZC5GaWx0ZXJTdW1t",
            "YXJ5SAASTQoLYWZmaWxpYXRpb24YAyABKAsyNi5zYWljLnZhbGt5cmllLnNk",
            "ay5nZW5lcmF0ZWQuVGhyZWF0QWZmaWxpYXRpb25SZXNwb25zZUgAElMKDmNs",
            "YXNzaWZpY2F0aW9uGAQgASgLMjkuc2FpYy52YWxreXJpZS5zZGsuZ2VuZXJh",
            "dGVkLlRocmVhdENsYXNzaWZpY2F0aW9uUmVzcG9uc2VIAEIGCgRkYXRhMrUI",
            "Cg5UaHJlYXRzTWFuYWdlchJOCgpnZXRWZXJzaW9uEhYuZ29vZ2xlLnByb3Rv",
            "YnVmLkVtcHR5Giguc2FpYy52YWxreXJpZS5zZGsuZ2VuZXJhdGVkLlZlcnNp",
            "b25JbmZvEocBCglzdWJzY3JpYmUSNy5zYWljLnZhbGt5cmllLnNkay5nZW5l",
            "cmF0ZWQuVGhyZWF0c01hbmFnZXJTdWJzY3JpcHRpb24aPy5zYWljLnZhbGt5",
            "cmllLnNkay5nZW5lcmF0ZWQuVGhyZWF0c01hbmFnZXJTdWJzY3JpcHRpb25S",
            "ZXNwb25zZTABEmoKCWFkZFRocmVhdBIyLnNhaWMudmFsa3lyaWUuc2RrLmdl",
            "bmVyYXRlZC5UaHJlYXRBZGRpdGlvbkRldGFpbHMaKS5zYWljLnZhbGt5cmll",
            "LnNkay5nZW5lcmF0ZWQuUmVzcG9uc2VJbmZvEm8KDnNldEFmZmlsaWF0aW9u",
            "EjIuc2FpYy52YWxreXJpZS5zZGsuZ2VuZXJhdGVkLlRhcmdldEFmZmlsaWF0",
            "aW9uSW5mbxopLnNhaWMudmFsa3lyaWUuc2RrLmdlbmVyYXRlZC5SZXNwb25z",
            "ZUluZm8SXwoPZ2V0QWZmaWxpYXRpb25zEhYuZ29vZ2xlLnByb3RvYnVmLkVt",
            "cHR5GjIuc2FpYy52YWxreXJpZS5zZGsuZ2VuZXJhdGVkLlRhcmdldEFmZmls",
            "aWF0aW9uSW5mbzABEnUKEXNldENsYXNzaWZpY2F0aW9uEjUuc2FpYy52YWxr",
            "eXJpZS5zZGsuZ2VuZXJhdGVkLlRhcmdldENsYXNzaWZpY2F0aW9uSW5mbxop",
            "LnNhaWMudmFsa3lyaWUuc2RrLmdlbmVyYXRlZC5SZXNwb25zZUluZm8SZQoS",
            "Z2V0Q2xhc3NpZmljYXRpb25zEhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5GjUu",
            "c2FpYy52YWxreXJpZS5zZGsuZ2VuZXJhdGVkLlRhcmdldENsYXNzaWZpY2F0",
            "aW9uSW5mbzABEk8KCmdldFRocmVhdHMSFi5nb29nbGUucHJvdG9idWYuRW1w",
            "dHkaJy5zYWljLnZhbGt5cmllLnNkay5nZW5lcmF0ZWQuVGhyZWF0SW5mbzAB",
            "EmkKCWdldFRocmVhdBIxLnNhaWMudmFsa3lyaWUuc2RrLmdlbmVyYXRlZC5U",
            "aHJlYXREZXRhaWxzUmVxdWVzdBonLnNhaWMudmFsa3lyaWUuc2RrLmdlbmVy",
            "YXRlZC5UaHJlYXRJbmZvMAEScQoSc3Vic2NyaWJlVG9IZWF0bWFwEisuc2Fp",
            "Yy52YWxreXJpZS5zZGsuZ2VuZXJhdGVkLkhlYXRtYXBSZXF1ZXN0Giwuc2Fp",
            "Yy52YWxreXJpZS5zZGsuZ2VuZXJhdGVkLkhlYXRtYXBSZXNwb25zZTABQm8K",
            "G3NhaWMudmFsa3lyaWUuc2RrLmdlbmVyYXRlZEITVGhyZWF0c01hbmFnZXJQ",
            "cm90b1okZ2l0aHViLmNvbS90bWhvbHQvR2VuRG9jUHJvdG8vc2RrL2dvqgIU",
            "U0FJQy5WYWxreXJpZS5BcGkuVjFiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, global::SAIC.Valkyrie.Api.V1.CommonReflection.Descriptor, global::SAIC.Valkyrie.Api.V1.ThreatsReflection.Descriptor, global::SAIC.Valkyrie.Api.V1.FilterReflection.Descriptor, global::SAIC.Valkyrie.Api.V1.HeatmapReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::SAIC.Valkyrie.Api.V1.ThreatDetailsRequest), global::SAIC.Valkyrie.Api.V1.ThreatDetailsRequest.Parser, new[]{ "ThreatId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::SAIC.Valkyrie.Api.V1.ThreatAdditionDetails), global::SAIC.Valkyrie.Api.V1.ThreatAdditionDetails.Parser, new[]{ "Threat" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::SAIC.Valkyrie.Api.V1.ThreatsManagerSubscription), global::SAIC.Valkyrie.Api.V1.ThreatsManagerSubscription.Parser, new[]{ "SubscribeToAffiliations", "SubscribeToThreats", "SubscribeToFilterSummary", "Filters", "SubscribeToClassifications" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::SAIC.Valkyrie.Api.V1.TargetClassificationInfo), global::SAIC.Valkyrie.Api.V1.TargetClassificationInfo.Parser, new[]{ "Target", "Classification" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::SAIC.Valkyrie.Api.V1.ThreatClassificationResponse), global::SAIC.Valkyrie.Api.V1.ThreatClassificationResponse.Parser, new[]{ "ClassificationInfo", "HasTimedOut" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::SAIC.Valkyrie.Api.V1.ThreatAffiliationResponse), global::SAIC.Valkyrie.Api.V1.ThreatAffiliationResponse.Parser, new[]{ "AffiliationInfo", "HasTimedOut" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::SAIC.Valkyrie.Api.V1.FilterSummary), global::SAIC.Valkyrie.Api.V1.FilterSummary.Parser, new[]{ "ThreatsFiltered" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::SAIC.Valkyrie.Api.V1.ThreatsManagerSubscriptionResponse), global::SAIC.Valkyrie.Api.V1.ThreatsManagerSubscriptionResponse.Parser, new[]{ "Threat", "FilterSummary", "Affiliation", "Classification" }, new[]{ "Data" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  ///
  /// The ThreatDetailsRequest message contains input details for the  {@link getThreat} call
  /// on the threats manager. Contains 1 or more threat ids to get the threat details for.
  /// </summary>
  public sealed partial class ThreatDetailsRequest : pb::IMessage<ThreatDetailsRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ThreatDetailsRequest> _parser = new pb::MessageParser<ThreatDetailsRequest>(() => new ThreatDetailsRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ThreatDetailsRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SAIC.Valkyrie.Api.V1.ThreatsManagerReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ThreatDetailsRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ThreatDetailsRequest(ThreatDetailsRequest other) : this() {
      threatId_ = other.threatId_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ThreatDetailsRequest Clone() {
      return new ThreatDetailsRequest(this);
    }

    /// <summary>Field number for the "threatId" field.</summary>
    public const int ThreatIdFieldNumber = 1;
    private static readonly pb::FieldCodec<long> _repeated_threatId_codec
        = pb::FieldCodec.ForInt64(10);
    private readonly pbc::RepeatedField<long> threatId_ = new pbc::RepeatedField<long>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<long> ThreatId {
      get { return threatId_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ThreatDetailsRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ThreatDetailsRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!threatId_.Equals(other.threatId_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= threatId_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      threatId_.WriteTo(output, _repeated_threatId_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      threatId_.WriteTo(ref output, _repeated_threatId_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += threatId_.CalculateSize(_repeated_threatId_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ThreatDetailsRequest other) {
      if (other == null) {
        return;
      }
      threatId_.Add(other.threatId_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10:
          case 8: {
            threatId_.AddEntriesFrom(input, _repeated_threatId_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10:
          case 8: {
            threatId_.AddEntriesFrom(ref input, _repeated_threatId_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ///
  /// The ThreatAdditionDetails message contains details for adding a threat into the Valkyrie system.
  /// NOTE: Keeping this around, even with one "detail," for possible future information keeping.
  /// </summary>
  public sealed partial class ThreatAdditionDetails : pb::IMessage<ThreatAdditionDetails>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ThreatAdditionDetails> _parser = new pb::MessageParser<ThreatAdditionDetails>(() => new ThreatAdditionDetails());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ThreatAdditionDetails> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SAIC.Valkyrie.Api.V1.ThreatsManagerReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ThreatAdditionDetails() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ThreatAdditionDetails(ThreatAdditionDetails other) : this() {
      threat_ = other.threat_ != null ? other.threat_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ThreatAdditionDetails Clone() {
      return new ThreatAdditionDetails(this);
    }

    /// <summary>Field number for the "threat" field.</summary>
    public const int ThreatFieldNumber = 2;
    private global::SAIC.Valkyrie.Api.V1.ThreatInfo threat_;
    /// <summary>
    /// the threat to be added
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::SAIC.Valkyrie.Api.V1.ThreatInfo Threat {
      get { return threat_; }
      set {
        threat_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ThreatAdditionDetails);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ThreatAdditionDetails other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Threat, other.Threat)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (threat_ != null) hash ^= Threat.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (threat_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Threat);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (threat_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Threat);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (threat_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Threat);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ThreatAdditionDetails other) {
      if (other == null) {
        return;
      }
      if (other.threat_ != null) {
        if (threat_ == null) {
          Threat = new global::SAIC.Valkyrie.Api.V1.ThreatInfo();
        }
        Threat.MergeFrom(other.Threat);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 18: {
            if (threat_ == null) {
              Threat = new global::SAIC.Valkyrie.Api.V1.ThreatInfo();
            }
            input.ReadMessage(Threat);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 18: {
            if (threat_ == null) {
              Threat = new global::SAIC.Valkyrie.Api.V1.ThreatInfo();
            }
            input.ReadMessage(Threat);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ///
  /// The ThreatsManagerSubscription message contains details for subscribing to the threats manager.
  /// This allows the client to choose the specifics for what to receive.
  /// </summary>
  public sealed partial class ThreatsManagerSubscription : pb::IMessage<ThreatsManagerSubscription>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ThreatsManagerSubscription> _parser = new pb::MessageParser<ThreatsManagerSubscription>(() => new ThreatsManagerSubscription());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ThreatsManagerSubscription> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SAIC.Valkyrie.Api.V1.ThreatsManagerReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ThreatsManagerSubscription() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ThreatsManagerSubscription(ThreatsManagerSubscription other) : this() {
      subscribeToAffiliations_ = other.subscribeToAffiliations_;
      subscribeToThreats_ = other.subscribeToThreats_;
      subscribeToFilterSummary_ = other.subscribeToFilterSummary_;
      filters_ = other.filters_ != null ? other.filters_.Clone() : null;
      subscribeToClassifications_ = other.subscribeToClassifications_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ThreatsManagerSubscription Clone() {
      return new ThreatsManagerSubscription(this);
    }

    /// <summary>Field number for the "subscribeToAffiliations" field.</summary>
    public const int SubscribeToAffiliationsFieldNumber = 1;
    private bool subscribeToAffiliations_;
    /// <summary>
    /// whether to subscribe to affiliations changes
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool SubscribeToAffiliations {
      get { return subscribeToAffiliations_; }
      set {
        subscribeToAffiliations_ = value;
      }
    }

    /// <summary>Field number for the "subscribeToThreats" field.</summary>
    public const int SubscribeToThreatsFieldNumber = 2;
    private bool subscribeToThreats_;
    /// <summary>
    /// whether to subscribe to outbound threats
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool SubscribeToThreats {
      get { return subscribeToThreats_; }
      set {
        subscribeToThreats_ = value;
      }
    }

    /// <summary>Field number for the "subscribeToFilterSummary" field.</summary>
    public const int SubscribeToFilterSummaryFieldNumber = 3;
    private bool subscribeToFilterSummary_;
    /// <summary>
    /// whether to subscribe to a filter summary
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool SubscribeToFilterSummary {
      get { return subscribeToFilterSummary_; }
      set {
        subscribeToFilterSummary_ = value;
      }
    }

    /// <summary>Field number for the "filters" field.</summary>
    public const int FiltersFieldNumber = 4;
    private global::SAIC.Valkyrie.Api.V1.FilterConfig filters_;
    /// <summary>
    /// filter to include. may contain many rules
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::SAIC.Valkyrie.Api.V1.FilterConfig Filters {
      get { return filters_; }
      set {
        filters_ = value;
      }
    }

    /// <summary>Field number for the "subscribeToClassifications" field.</summary>
    public const int SubscribeToClassificationsFieldNumber = 5;
    private bool subscribeToClassifications_;
    /// <summary>
    /// whether to subscribe to classifications changes
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool SubscribeToClassifications {
      get { return subscribeToClassifications_; }
      set {
        subscribeToClassifications_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ThreatsManagerSubscription);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ThreatsManagerSubscription other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (SubscribeToAffiliations != other.SubscribeToAffiliations) return false;
      if (SubscribeToThreats != other.SubscribeToThreats) return false;
      if (SubscribeToFilterSummary != other.SubscribeToFilterSummary) return false;
      if (!object.Equals(Filters, other.Filters)) return false;
      if (SubscribeToClassifications != other.SubscribeToClassifications) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (SubscribeToAffiliations != false) hash ^= SubscribeToAffiliations.GetHashCode();
      if (SubscribeToThreats != false) hash ^= SubscribeToThreats.GetHashCode();
      if (SubscribeToFilterSummary != false) hash ^= SubscribeToFilterSummary.GetHashCode();
      if (filters_ != null) hash ^= Filters.GetHashCode();
      if (SubscribeToClassifications != false) hash ^= SubscribeToClassifications.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (SubscribeToAffiliations != false) {
        output.WriteRawTag(8);
        output.WriteBool(SubscribeToAffiliations);
      }
      if (SubscribeToThreats != false) {
        output.WriteRawTag(16);
        output.WriteBool(SubscribeToThreats);
      }
      if (SubscribeToFilterSummary != false) {
        output.WriteRawTag(24);
        output.WriteBool(SubscribeToFilterSummary);
      }
      if (filters_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Filters);
      }
      if (SubscribeToClassifications != false) {
        output.WriteRawTag(40);
        output.WriteBool(SubscribeToClassifications);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (SubscribeToAffiliations != false) {
        output.WriteRawTag(8);
        output.WriteBool(SubscribeToAffiliations);
      }
      if (SubscribeToThreats != false) {
        output.WriteRawTag(16);
        output.WriteBool(SubscribeToThreats);
      }
      if (SubscribeToFilterSummary != false) {
        output.WriteRawTag(24);
        output.WriteBool(SubscribeToFilterSummary);
      }
      if (filters_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Filters);
      }
      if (SubscribeToClassifications != false) {
        output.WriteRawTag(40);
        output.WriteBool(SubscribeToClassifications);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (SubscribeToAffiliations != false) {
        size += 1 + 1;
      }
      if (SubscribeToThreats != false) {
        size += 1 + 1;
      }
      if (SubscribeToFilterSummary != false) {
        size += 1 + 1;
      }
      if (filters_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Filters);
      }
      if (SubscribeToClassifications != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ThreatsManagerSubscription other) {
      if (other == null) {
        return;
      }
      if (other.SubscribeToAffiliations != false) {
        SubscribeToAffiliations = other.SubscribeToAffiliations;
      }
      if (other.SubscribeToThreats != false) {
        SubscribeToThreats = other.SubscribeToThreats;
      }
      if (other.SubscribeToFilterSummary != false) {
        SubscribeToFilterSummary = other.SubscribeToFilterSummary;
      }
      if (other.filters_ != null) {
        if (filters_ == null) {
          Filters = new global::SAIC.Valkyrie.Api.V1.FilterConfig();
        }
        Filters.MergeFrom(other.Filters);
      }
      if (other.SubscribeToClassifications != false) {
        SubscribeToClassifications = other.SubscribeToClassifications;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            SubscribeToAffiliations = input.ReadBool();
            break;
          }
          case 16: {
            SubscribeToThreats = input.ReadBool();
            break;
          }
          case 24: {
            SubscribeToFilterSummary = input.ReadBool();
            break;
          }
          case 34: {
            if (filters_ == null) {
              Filters = new global::SAIC.Valkyrie.Api.V1.FilterConfig();
            }
            input.ReadMessage(Filters);
            break;
          }
          case 40: {
            SubscribeToClassifications = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            SubscribeToAffiliations = input.ReadBool();
            break;
          }
          case 16: {
            SubscribeToThreats = input.ReadBool();
            break;
          }
          case 24: {
            SubscribeToFilterSummary = input.ReadBool();
            break;
          }
          case 34: {
            if (filters_ == null) {
              Filters = new global::SAIC.Valkyrie.Api.V1.FilterConfig();
            }
            input.ReadMessage(Filters);
            break;
          }
          case 40: {
            SubscribeToClassifications = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ///
  /// The TargetClassificationInfo message contains details for setting (or getting) the
  /// classification type for a target given its ID.
  /// </summary>
  public sealed partial class TargetClassificationInfo : pb::IMessage<TargetClassificationInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TargetClassificationInfo> _parser = new pb::MessageParser<TargetClassificationInfo>(() => new TargetClassificationInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TargetClassificationInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SAIC.Valkyrie.Api.V1.ThreatsManagerReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TargetClassificationInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TargetClassificationInfo(TargetClassificationInfo other) : this() {
      target_ = other.target_ != null ? other.target_.Clone() : null;
      classification_ = other.classification_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TargetClassificationInfo Clone() {
      return new TargetClassificationInfo(this);
    }

    /// <summary>Field number for the "target" field.</summary>
    public const int TargetFieldNumber = 1;
    private global::SAIC.Valkyrie.Api.V1.TargetIdentifier target_;
    /// <summary>
    /// the target
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::SAIC.Valkyrie.Api.V1.TargetIdentifier Target {
      get { return target_; }
      set {
        target_ = value;
      }
    }

    /// <summary>Field number for the "classification" field.</summary>
    public const int ClassificationFieldNumber = 2;
    private global::SAIC.Valkyrie.Api.V1.TargetClassification classification_ = global::SAIC.Valkyrie.Api.V1.TargetClassification.ClassTypePending;
    /// <summary>
    /// the classification of the target
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::SAIC.Valkyrie.Api.V1.TargetClassification Classification {
      get { return classification_; }
      set {
        classification_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TargetClassificationInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TargetClassificationInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Target, other.Target)) return false;
      if (Classification != other.Classification) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (target_ != null) hash ^= Target.GetHashCode();
      if (Classification != global::SAIC.Valkyrie.Api.V1.TargetClassification.ClassTypePending) hash ^= Classification.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (target_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Target);
      }
      if (Classification != global::SAIC.Valkyrie.Api.V1.TargetClassification.ClassTypePending) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Classification);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (target_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Target);
      }
      if (Classification != global::SAIC.Valkyrie.Api.V1.TargetClassification.ClassTypePending) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Classification);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (target_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Target);
      }
      if (Classification != global::SAIC.Valkyrie.Api.V1.TargetClassification.ClassTypePending) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Classification);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TargetClassificationInfo other) {
      if (other == null) {
        return;
      }
      if (other.target_ != null) {
        if (target_ == null) {
          Target = new global::SAIC.Valkyrie.Api.V1.TargetIdentifier();
        }
        Target.MergeFrom(other.Target);
      }
      if (other.Classification != global::SAIC.Valkyrie.Api.V1.TargetClassification.ClassTypePending) {
        Classification = other.Classification;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (target_ == null) {
              Target = new global::SAIC.Valkyrie.Api.V1.TargetIdentifier();
            }
            input.ReadMessage(Target);
            break;
          }
          case 16: {
            Classification = (global::SAIC.Valkyrie.Api.V1.TargetClassification) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (target_ == null) {
              Target = new global::SAIC.Valkyrie.Api.V1.TargetIdentifier();
            }
            input.ReadMessage(Target);
            break;
          }
          case 16: {
            Classification = (global::SAIC.Valkyrie.Api.V1.TargetClassification) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ///
  /// The ThreatClassificationResponse message provides the details for a change to a threat's classification.
  /// Sent as part of a client subscription.
  /// </summary>
  public sealed partial class ThreatClassificationResponse : pb::IMessage<ThreatClassificationResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ThreatClassificationResponse> _parser = new pb::MessageParser<ThreatClassificationResponse>(() => new ThreatClassificationResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ThreatClassificationResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SAIC.Valkyrie.Api.V1.ThreatsManagerReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ThreatClassificationResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ThreatClassificationResponse(ThreatClassificationResponse other) : this() {
      classificationInfo_ = other.classificationInfo_ != null ? other.classificationInfo_.Clone() : null;
      hasTimedOut_ = other.hasTimedOut_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ThreatClassificationResponse Clone() {
      return new ThreatClassificationResponse(this);
    }

    /// <summary>Field number for the "classificationInfo" field.</summary>
    public const int ClassificationInfoFieldNumber = 1;
    private global::SAIC.Valkyrie.Api.V1.TargetClassificationInfo classificationInfo_;
    /// <summary>
    /// the user classification info
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::SAIC.Valkyrie.Api.V1.TargetClassificationInfo ClassificationInfo {
      get { return classificationInfo_; }
      set {
        classificationInfo_ = value;
      }
    }

    /// <summary>Field number for the "hasTimedOut" field.</summary>
    public const int HasTimedOutFieldNumber = 2;
    private bool hasTimedOut_;
    /// <summary>
    /// whether the threat has timed out. Useful in case the client is not also subscribed to threats.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasTimedOut {
      get { return hasTimedOut_; }
      set {
        hasTimedOut_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ThreatClassificationResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ThreatClassificationResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(ClassificationInfo, other.ClassificationInfo)) return false;
      if (HasTimedOut != other.HasTimedOut) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (classificationInfo_ != null) hash ^= ClassificationInfo.GetHashCode();
      if (HasTimedOut != false) hash ^= HasTimedOut.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (classificationInfo_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(ClassificationInfo);
      }
      if (HasTimedOut != false) {
        output.WriteRawTag(16);
        output.WriteBool(HasTimedOut);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (classificationInfo_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(ClassificationInfo);
      }
      if (HasTimedOut != false) {
        output.WriteRawTag(16);
        output.WriteBool(HasTimedOut);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (classificationInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ClassificationInfo);
      }
      if (HasTimedOut != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ThreatClassificationResponse other) {
      if (other == null) {
        return;
      }
      if (other.classificationInfo_ != null) {
        if (classificationInfo_ == null) {
          ClassificationInfo = new global::SAIC.Valkyrie.Api.V1.TargetClassificationInfo();
        }
        ClassificationInfo.MergeFrom(other.ClassificationInfo);
      }
      if (other.HasTimedOut != false) {
        HasTimedOut = other.HasTimedOut;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (classificationInfo_ == null) {
              ClassificationInfo = new global::SAIC.Valkyrie.Api.V1.TargetClassificationInfo();
            }
            input.ReadMessage(ClassificationInfo);
            break;
          }
          case 16: {
            HasTimedOut = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (classificationInfo_ == null) {
              ClassificationInfo = new global::SAIC.Valkyrie.Api.V1.TargetClassificationInfo();
            }
            input.ReadMessage(ClassificationInfo);
            break;
          }
          case 16: {
            HasTimedOut = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ///
  /// The ThreatAffiliationResponse message provides the details for a change to a threat's affiliation.
  /// Sent as part of a client subscription.
  /// </summary>
  public sealed partial class ThreatAffiliationResponse : pb::IMessage<ThreatAffiliationResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ThreatAffiliationResponse> _parser = new pb::MessageParser<ThreatAffiliationResponse>(() => new ThreatAffiliationResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ThreatAffiliationResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SAIC.Valkyrie.Api.V1.ThreatsManagerReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ThreatAffiliationResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ThreatAffiliationResponse(ThreatAffiliationResponse other) : this() {
      affiliationInfo_ = other.affiliationInfo_ != null ? other.affiliationInfo_.Clone() : null;
      hasTimedOut_ = other.hasTimedOut_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ThreatAffiliationResponse Clone() {
      return new ThreatAffiliationResponse(this);
    }

    /// <summary>Field number for the "affiliationInfo" field.</summary>
    public const int AffiliationInfoFieldNumber = 1;
    private global::SAIC.Valkyrie.Api.V1.TargetAffiliationInfo affiliationInfo_;
    /// <summary>
    /// the user affiliation info
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::SAIC.Valkyrie.Api.V1.TargetAffiliationInfo AffiliationInfo {
      get { return affiliationInfo_; }
      set {
        affiliationInfo_ = value;
      }
    }

    /// <summary>Field number for the "hasTimedOut" field.</summary>
    public const int HasTimedOutFieldNumber = 2;
    private bool hasTimedOut_;
    /// <summary>
    /// whether the threat has timed out. Useful in case the client is not also subscribed to threats.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasTimedOut {
      get { return hasTimedOut_; }
      set {
        hasTimedOut_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ThreatAffiliationResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ThreatAffiliationResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(AffiliationInfo, other.AffiliationInfo)) return false;
      if (HasTimedOut != other.HasTimedOut) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (affiliationInfo_ != null) hash ^= AffiliationInfo.GetHashCode();
      if (HasTimedOut != false) hash ^= HasTimedOut.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (affiliationInfo_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(AffiliationInfo);
      }
      if (HasTimedOut != false) {
        output.WriteRawTag(16);
        output.WriteBool(HasTimedOut);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (affiliationInfo_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(AffiliationInfo);
      }
      if (HasTimedOut != false) {
        output.WriteRawTag(16);
        output.WriteBool(HasTimedOut);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (affiliationInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(AffiliationInfo);
      }
      if (HasTimedOut != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ThreatAffiliationResponse other) {
      if (other == null) {
        return;
      }
      if (other.affiliationInfo_ != null) {
        if (affiliationInfo_ == null) {
          AffiliationInfo = new global::SAIC.Valkyrie.Api.V1.TargetAffiliationInfo();
        }
        AffiliationInfo.MergeFrom(other.AffiliationInfo);
      }
      if (other.HasTimedOut != false) {
        HasTimedOut = other.HasTimedOut;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (affiliationInfo_ == null) {
              AffiliationInfo = new global::SAIC.Valkyrie.Api.V1.TargetAffiliationInfo();
            }
            input.ReadMessage(AffiliationInfo);
            break;
          }
          case 16: {
            HasTimedOut = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (affiliationInfo_ == null) {
              AffiliationInfo = new global::SAIC.Valkyrie.Api.V1.TargetAffiliationInfo();
            }
            input.ReadMessage(AffiliationInfo);
            break;
          }
          case 16: {
            HasTimedOut = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ///
  /// The FilterSummary message contains a count of how many threats have been filtered out of the result
  /// set for a given client. This is sent periodically to a client if subscribeToFilterSummary is set to true
  /// when subscribing.
  /// </summary>
  public sealed partial class FilterSummary : pb::IMessage<FilterSummary>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<FilterSummary> _parser = new pb::MessageParser<FilterSummary>(() => new FilterSummary());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<FilterSummary> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SAIC.Valkyrie.Api.V1.ThreatsManagerReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FilterSummary() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FilterSummary(FilterSummary other) : this() {
      threatsFiltered_ = other.threatsFiltered_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FilterSummary Clone() {
      return new FilterSummary(this);
    }

    /// <summary>Field number for the "threatsFiltered" field.</summary>
    public const int ThreatsFilteredFieldNumber = 1;
    private long threatsFiltered_;
    /// <summary>
    /// The number of threats that have been filtered
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long ThreatsFiltered {
      get { return threatsFiltered_; }
      set {
        threatsFiltered_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as FilterSummary);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(FilterSummary other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ThreatsFiltered != other.ThreatsFiltered) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ThreatsFiltered != 0L) hash ^= ThreatsFiltered.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ThreatsFiltered != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(ThreatsFiltered);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ThreatsFiltered != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(ThreatsFiltered);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ThreatsFiltered != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(ThreatsFiltered);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(FilterSummary other) {
      if (other == null) {
        return;
      }
      if (other.ThreatsFiltered != 0L) {
        ThreatsFiltered = other.ThreatsFiltered;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ThreatsFiltered = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ThreatsFiltered = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ///
  /// The ThreatsManagerSubscriptionResponse message is the top level wrapper message sent to a subscribed
  /// client it contains one of 4 possible message types - a threat, filter summary, affiliation change, or
  /// classification change. Only one of these values will be set. A client will only receive the type of
  /// responses requested when subscribing.
  /// </summary>
  public sealed partial class ThreatsManagerSubscriptionResponse : pb::IMessage<ThreatsManagerSubscriptionResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ThreatsManagerSubscriptionResponse> _parser = new pb::MessageParser<ThreatsManagerSubscriptionResponse>(() => new ThreatsManagerSubscriptionResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ThreatsManagerSubscriptionResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SAIC.Valkyrie.Api.V1.ThreatsManagerReflection.Descriptor.MessageTypes[7]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ThreatsManagerSubscriptionResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ThreatsManagerSubscriptionResponse(ThreatsManagerSubscriptionResponse other) : this() {
      switch (other.DataCase) {
        case DataOneofCase.Threat:
          Threat = other.Threat.Clone();
          break;
        case DataOneofCase.FilterSummary:
          FilterSummary = other.FilterSummary.Clone();
          break;
        case DataOneofCase.Affiliation:
          Affiliation = other.Affiliation.Clone();
          break;
        case DataOneofCase.Classification:
          Classification = other.Classification.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ThreatsManagerSubscriptionResponse Clone() {
      return new ThreatsManagerSubscriptionResponse(this);
    }

    /// <summary>Field number for the "threat" field.</summary>
    public const int ThreatFieldNumber = 1;
    /// <summary>
    /// A ThreatInfo message containing the details of a threat
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::SAIC.Valkyrie.Api.V1.ThreatInfo Threat {
      get { return dataCase_ == DataOneofCase.Threat ? (global::SAIC.Valkyrie.Api.V1.ThreatInfo) data_ : null; }
      set {
        data_ = value;
        dataCase_ = value == null ? DataOneofCase.None : DataOneofCase.Threat;
      }
    }

    /// <summary>Field number for the "filterSummary" field.</summary>
    public const int FilterSummaryFieldNumber = 2;
    /// <summary>
    /// A message containing the number of threats that have been filtered
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::SAIC.Valkyrie.Api.V1.FilterSummary FilterSummary {
      get { return dataCase_ == DataOneofCase.FilterSummary ? (global::SAIC.Valkyrie.Api.V1.FilterSummary) data_ : null; }
      set {
        data_ = value;
        dataCase_ = value == null ? DataOneofCase.None : DataOneofCase.FilterSummary;
      }
    }

    /// <summary>Field number for the "affiliation" field.</summary>
    public const int AffiliationFieldNumber = 3;
    /// <summary>
    /// A message containing user affiliation changes
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::SAIC.Valkyrie.Api.V1.ThreatAffiliationResponse Affiliation {
      get { return dataCase_ == DataOneofCase.Affiliation ? (global::SAIC.Valkyrie.Api.V1.ThreatAffiliationResponse) data_ : null; }
      set {
        data_ = value;
        dataCase_ = value == null ? DataOneofCase.None : DataOneofCase.Affiliation;
      }
    }

    /// <summary>Field number for the "classification" field.</summary>
    public const int ClassificationFieldNumber = 4;
    /// <summary>
    /// A message containing user classification changes
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::SAIC.Valkyrie.Api.V1.ThreatClassificationResponse Classification {
      get { return dataCase_ == DataOneofCase.Classification ? (global::SAIC.Valkyrie.Api.V1.ThreatClassificationResponse) data_ : null; }
      set {
        data_ = value;
        dataCase_ = value == null ? DataOneofCase.None : DataOneofCase.Classification;
      }
    }

    private object data_;
    /// <summary>Enum of possible cases for the "data" oneof.</summary>
    public enum DataOneofCase {
      None = 0,
      Threat = 1,
      FilterSummary = 2,
      Affiliation = 3,
      Classification = 4,
    }
    private DataOneofCase dataCase_ = DataOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DataOneofCase DataCase {
      get { return dataCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearData() {
      dataCase_ = DataOneofCase.None;
      data_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ThreatsManagerSubscriptionResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ThreatsManagerSubscriptionResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Threat, other.Threat)) return false;
      if (!object.Equals(FilterSummary, other.FilterSummary)) return false;
      if (!object.Equals(Affiliation, other.Affiliation)) return false;
      if (!object.Equals(Classification, other.Classification)) return false;
      if (DataCase != other.DataCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (dataCase_ == DataOneofCase.Threat) hash ^= Threat.GetHashCode();
      if (dataCase_ == DataOneofCase.FilterSummary) hash ^= FilterSummary.GetHashCode();
      if (dataCase_ == DataOneofCase.Affiliation) hash ^= Affiliation.GetHashCode();
      if (dataCase_ == DataOneofCase.Classification) hash ^= Classification.GetHashCode();
      hash ^= (int) dataCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (dataCase_ == DataOneofCase.Threat) {
        output.WriteRawTag(10);
        output.WriteMessage(Threat);
      }
      if (dataCase_ == DataOneofCase.FilterSummary) {
        output.WriteRawTag(18);
        output.WriteMessage(FilterSummary);
      }
      if (dataCase_ == DataOneofCase.Affiliation) {
        output.WriteRawTag(26);
        output.WriteMessage(Affiliation);
      }
      if (dataCase_ == DataOneofCase.Classification) {
        output.WriteRawTag(34);
        output.WriteMessage(Classification);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (dataCase_ == DataOneofCase.Threat) {
        output.WriteRawTag(10);
        output.WriteMessage(Threat);
      }
      if (dataCase_ == DataOneofCase.FilterSummary) {
        output.WriteRawTag(18);
        output.WriteMessage(FilterSummary);
      }
      if (dataCase_ == DataOneofCase.Affiliation) {
        output.WriteRawTag(26);
        output.WriteMessage(Affiliation);
      }
      if (dataCase_ == DataOneofCase.Classification) {
        output.WriteRawTag(34);
        output.WriteMessage(Classification);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (dataCase_ == DataOneofCase.Threat) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Threat);
      }
      if (dataCase_ == DataOneofCase.FilterSummary) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(FilterSummary);
      }
      if (dataCase_ == DataOneofCase.Affiliation) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Affiliation);
      }
      if (dataCase_ == DataOneofCase.Classification) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Classification);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ThreatsManagerSubscriptionResponse other) {
      if (other == null) {
        return;
      }
      switch (other.DataCase) {
        case DataOneofCase.Threat:
          if (Threat == null) {
            Threat = new global::SAIC.Valkyrie.Api.V1.ThreatInfo();
          }
          Threat.MergeFrom(other.Threat);
          break;
        case DataOneofCase.FilterSummary:
          if (FilterSummary == null) {
            FilterSummary = new global::SAIC.Valkyrie.Api.V1.FilterSummary();
          }
          FilterSummary.MergeFrom(other.FilterSummary);
          break;
        case DataOneofCase.Affiliation:
          if (Affiliation == null) {
            Affiliation = new global::SAIC.Valkyrie.Api.V1.ThreatAffiliationResponse();
          }
          Affiliation.MergeFrom(other.Affiliation);
          break;
        case DataOneofCase.Classification:
          if (Classification == null) {
            Classification = new global::SAIC.Valkyrie.Api.V1.ThreatClassificationResponse();
          }
          Classification.MergeFrom(other.Classification);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            global::SAIC.Valkyrie.Api.V1.ThreatInfo subBuilder = new global::SAIC.Valkyrie.Api.V1.ThreatInfo();
            if (dataCase_ == DataOneofCase.Threat) {
              subBuilder.MergeFrom(Threat);
            }
            input.ReadMessage(subBuilder);
            Threat = subBuilder;
            break;
          }
          case 18: {
            global::SAIC.Valkyrie.Api.V1.FilterSummary subBuilder = new global::SAIC.Valkyrie.Api.V1.FilterSummary();
            if (dataCase_ == DataOneofCase.FilterSummary) {
              subBuilder.MergeFrom(FilterSummary);
            }
            input.ReadMessage(subBuilder);
            FilterSummary = subBuilder;
            break;
          }
          case 26: {
            global::SAIC.Valkyrie.Api.V1.ThreatAffiliationResponse subBuilder = new global::SAIC.Valkyrie.Api.V1.ThreatAffiliationResponse();
            if (dataCase_ == DataOneofCase.Affiliation) {
              subBuilder.MergeFrom(Affiliation);
            }
            input.ReadMessage(subBuilder);
            Affiliation = subBuilder;
            break;
          }
          case 34: {
            global::SAIC.Valkyrie.Api.V1.ThreatClassificationResponse subBuilder = new global::SAIC.Valkyrie.Api.V1.ThreatClassificationResponse();
            if (dataCase_ == DataOneofCase.Classification) {
              subBuilder.MergeFrom(Classification);
            }
            input.ReadMessage(subBuilder);
            Classification = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            global::SAIC.Valkyrie.Api.V1.ThreatInfo subBuilder = new global::SAIC.Valkyrie.Api.V1.ThreatInfo();
            if (dataCase_ == DataOneofCase.Threat) {
              subBuilder.MergeFrom(Threat);
            }
            input.ReadMessage(subBuilder);
            Threat = subBuilder;
            break;
          }
          case 18: {
            global::SAIC.Valkyrie.Api.V1.FilterSummary subBuilder = new global::SAIC.Valkyrie.Api.V1.FilterSummary();
            if (dataCase_ == DataOneofCase.FilterSummary) {
              subBuilder.MergeFrom(FilterSummary);
            }
            input.ReadMessage(subBuilder);
            FilterSummary = subBuilder;
            break;
          }
          case 26: {
            global::SAIC.Valkyrie.Api.V1.ThreatAffiliationResponse subBuilder = new global::SAIC.Valkyrie.Api.V1.ThreatAffiliationResponse();
            if (dataCase_ == DataOneofCase.Affiliation) {
              subBuilder.MergeFrom(Affiliation);
            }
            input.ReadMessage(subBuilder);
            Affiliation = subBuilder;
            break;
          }
          case 34: {
            global::SAIC.Valkyrie.Api.V1.ThreatClassificationResponse subBuilder = new global::SAIC.Valkyrie.Api.V1.ThreatClassificationResponse();
            if (dataCase_ == DataOneofCase.Classification) {
              subBuilder.MergeFrom(Classification);
            }
            input.ReadMessage(subBuilder);
            Classification = subBuilder;
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
